-- Agent-run execution registration (Phase 4A; controller-integration D6 node_executions table).
--
-- The control-plane A side owns node_executions: it records the authoritative registration of a
-- dispatched execution — the Controller-generated execution_id, the target Node, the immutable
-- dispatch input, the dispatch lease epoch, and (from Phase 4B) the largest taken Node event
-- sequence. B never writes it; a Controller reaches it only through the agent_work_dispatch
-- control action inside its lease-validated transaction (D-020/D-021), exactly as clone_dispatch
-- registers clone_executions.
--
-- One execution_work → at most one node_execution: work_id is UNIQUE and references
-- execution_work(id), so a queued work item can never be registered to two executions. The
-- insertion is atomic with the execution_work.execution_id fence (UPDATE ... WHERE execution_id
-- IS NULL) in the same dispatch transaction, so the execution and its work binding commit
-- together and a fence failure rolls both back — no orphan node_executions row can outlive an
-- unbound work item (mandate §9/§10).
--
-- execution_id is the globally authoritative execution identity and the PRIMARY KEY. It is
-- generated by the Controller and supplied on agent_work_dispatch; A records it and fences the
-- work binding, never generating the identity value (D-020). dispatched_epoch is the
-- lease-validated epoch at dispatch, fencing a stale worker's later writes (clone precedent).
-- last_event_sequence mirrors the largest Node event sequence taken so far and DEFAULTs to 0; it
-- is only advanced by Phase 4B takeovers — Phase 4A creates and reads the initial value only, and
-- never threads it into any seq allocation (D-023 stays a Phase 4B proposal).
--
-- operation_id is a semantic reference to the IssueRun (issue_runs.id) the work belongs to — a
-- Controller convenience denormalized from the work. Run integrity does not depend on it: the
-- ownership path node_executions → execution_work → issue_runs carries the run/workspace
-- references through work_id's FK, so node_executions holds no direct B-owned issue_runs binding.
CREATE TABLE node_executions (
  execution_id text PRIMARY KEY CHECK(length(execution_id) BETWEEN 1 AND 200),
  kind text NOT NULL CHECK(kind IN ('agent_session','deliver_revision')),
  operation_id uuid NOT NULL,
  work_id uuid NOT NULL UNIQUE REFERENCES execution_work(id),
  node_id text NOT NULL CHECK(length(node_id) BETWEEN 1 AND 200),
  input jsonb NOT NULL CHECK(jsonb_typeof(input)='object'),
  result jsonb CHECK(result IS NULL OR jsonb_typeof(result)='object'),
  dispatched_epoch bigint NOT NULL CHECK(dispatched_epoch>0),
  last_event_sequence bigint NOT NULL DEFAULT 0 CHECK(last_event_sequence>=0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
-- C2 registration recovery: a Controller that committed a dispatch before its Node received it
-- discovers the still-in-flight (result IS NULL) execution by the target Node without holding a
-- lease, then reuses the recorded execution_id instead of registering a second one.
CREATE INDEX node_executions_pending_node
  ON node_executions(node_id, created_at) WHERE result IS NULL;