-- Preserve creation order even when commands are accepted in one transaction (now() is constant).
-- Existing commands keep the previous created_at/id order; new commands receive a monotonic ordinal.
ALTER TABLE thread_commands ADD COLUMN queue_sequence bigint GENERATED BY DEFAULT AS IDENTITY;
WITH ordered AS (
 SELECT id,row_number() OVER (ORDER BY created_at,id) AS ordinal FROM thread_commands
)
UPDATE thread_commands c SET queue_sequence=o.ordinal FROM ordered o WHERE c.id=o.id;
SELECT setval(pg_get_serial_sequence('thread_commands','queue_sequence'),
 COALESCE((SELECT max(queue_sequence)+1 FROM thread_commands),1),false);
CREATE UNIQUE INDEX thread_command_order ON thread_commands(queue_sequence);

-- A run has one session for its lifetime; only delivery attempts may be retried as new executions.
CREATE UNIQUE INDEX one_session_per_run ON node_executions(operation_id) WHERE kind='agent_session';
