/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
export type AccessAllowedAction = typeof AccessAllowedAction[keyof typeof AccessAllowedAction];


export const AccessAllowedAction = {
  read: 'read',
  execute: 'execute',
} as const;

export interface Access {
  allowedAction: AccessAllowedAction;
  executable: boolean;
  runtimeGeneration: number;
  tenantId: string;
  userId: string;
  workspaceId: string;
}

export interface AdminOperation {
  createdAt: string;
  id: string;
  kind: string;
  projectId: string;
  state: string;
  step: string;
  tenantId: string;
  updatedAt: string;
  version: number;
  /** @nullable */
  workspaceId: string | null;
}

export type AdminResourceDesiredState = typeof AdminResourceDesiredState[keyof typeof AdminResourceDesiredState];


export const AdminResourceDesiredState = {
  running: 'running',
  stopped: 'stopped',
  deleted: 'deleted',
} as const;

export type AdminResourceKind = typeof AdminResourceKind[keyof typeof AdminResourceKind];


export const AdminResourceKind = {
  main: 'main',
  isolated: 'isolated',
} as const;

export type AdminResourceObservedState = typeof AdminResourceObservedState[keyof typeof AdminResourceObservedState];


export const AdminResourceObservedState = {
  provisioning: 'provisioning',
  starting: 'starting',
  ready: 'ready',
  stopping: 'stopping',
  stopped: 'stopped',
  unavailable: 'unavailable',
  deleting: 'deleting',
  deleted: 'deleted',
} as const;

export interface AdminResource {
  desiredState: AdminResourceDesiredState;
  id: string;
  kind: AdminResourceKind;
  observedState: AdminResourceObservedState;
  ownerUserId: string;
  projectId: string;
  runtimeGeneration: number;
  version: number;
}

export type CloneStateKind = typeof CloneStateKind[keyof typeof CloneStateKind];


export const CloneStateKind = {
  pending: 'pending',
  succeeded: 'succeeded',
  failed: 'failed',
} as const;

export type CloneStateReason = typeof CloneStateReason[keyof typeof CloneStateReason];


export const CloneStateReason = {
  sourceUnavailable: 'sourceUnavailable',
  branchNotFound: 'branchNotFound',
  destinationConflict: 'destinationConflict',
  operationFailed: 'operationFailed',
  unspecified: 'unspecified',
} as const;

export interface CloneState {
  commit?: string;
  kind: CloneStateKind;
  path?: string;
  reason?: CloneStateReason;
  retainedPath?: string;
}

export interface CloneOperation {
  branch: string;
  createdAt: string;
  /** @nullable */
  executionId: string | null;
  /** @nullable */
  nodeId: string | null;
  operationId: string;
  repository: string;
  requestId: string;
  state: CloneState;
  updatedAt: string;
}

export interface ControllerProject {
  createdAt: string;
  /** @nullable */
  credentialRefId: string | null;
  defaultBranch: string;
  /** @nullable */
  deletedAt: string | null;
  id: string;
  lifecycle: string;
  name: string;
  ownerUserId: string;
  repositoryUrl: string;
  /** @nullable */
  secretRef: string | null;
  spaceId: string;
  tenantId: string;
  version: number;
}

export interface ControllerWorkspace {
  admissionEpoch: number;
  admissionOpen: boolean;
  /**
     * @nullable
     * @pattern ^([0-9a-f]{40}|[0-9a-f]{64})$
     */
  baseCommitId: string | null;
  branchName: string;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  desiredState: string;
  id: string;
  kind: string;
  observedState: string;
  ownerUserId: string;
  projectId: string;
  relativePath: string;
  requestedRef: string;
  runtimeGeneration: number;
  tenantId: string;
  version: number;
}

export type EffectRequestKind = typeof EffectRequestKind[keyof typeof EffectRequestKind];


export const EffectRequestKind = {
  storage_ensure: 'storage_ensure',
  worktree_ensure: 'worktree_ensure',
  sandbox_ensure: 'sandbox_ensure',
  sandbox_terminate: 'sandbox_terminate',
  worktree_delete: 'worktree_delete',
  storage_delete: 'storage_delete',
} as const;

export interface EffectRequest {
  kind: EffectRequestKind;
  projectId: string;
  repositoryUrl?: string;
  requestedRef?: string;
  sandboxInstanceId?: string;
  workspaceId?: string;
}

export interface EffectResult {
  /** @pattern ^([0-9a-f]{40}|[0-9a-f]{64})$ */
  commitId?: string;
  jobTerminated?: boolean;
  layoutVersion?: number;
  nodeId?: string;
  removed?: boolean;
  sandboxInstanceId?: string;
  terminated?: boolean;
}

export interface Effect {
  createdAt: string;
  /** @nullable */
  externalId: string | null;
  id: string;
  kind: string;
  operationId: string;
  projectId: string;
  reconciledEpoch: number;
  request: EffectRequest;
  result: EffectResult;
  state: string;
  version: number;
  /** @nullable */
  workspaceId: string | null;
}

/**
 * @nullable
 */
export type EmptyClaimOperation = typeof EmptyClaimOperation[keyof typeof EmptyClaimOperation] | null;


export const EmptyClaimOperation = {
} as const;

export interface EmptyClaim {
  /** @nullable */
  operation: EmptyClaimOperation;
}

export type ErrorParams = { [key: string]: unknown };

export interface Error {
  code: string;
  params: ErrorParams;
  requestId: string;
}

export type IdleRefusalErrorCode = typeof IdleRefusalErrorCode[keyof typeof IdleRefusalErrorCode];


export const IdleRefusalErrorCode = {
  resource_in_use: 'resource_in_use',
} as const;

export interface IdleRefusal {
  accepted: boolean;
  errorCode: IdleRefusalErrorCode;
}

export interface Lease {
  epoch: number;
  expiresAt: string;
  holderId: string;
  name: string;
}

export interface Member {
  createdAt: string;
  role: string;
  status: string;
  tenantId: string;
  userId: string;
  version: number;
}

export interface MemberListItem {
  displayName: string;
  id: string;
  role: string;
  status: string;
  tenantId: string;
  userId: string;
  version: number;
}

export interface Node {
  connectionState: string;
  /** @nullable */
  endedAt: string | null;
  id: string;
  /** @nullable */
  idleAdmissionEpoch: number | null;
  initialized: boolean;
  lastSeenAt: string;
  protocolVersion: number;
  sandboxInstanceId: string;
  serviceSubject: string;
  version: number;
  workspaceId: string;
}

export type OperationState = typeof OperationState[keyof typeof OperationState];


export const OperationState = {
  queued: 'queued',
  running: 'running',
  retry_wait: 'retry_wait',
  blocked: 'blocked',
  succeeded: 'succeeded',
  failed: 'failed',
} as const;

export type OperationStep = typeof OperationStep[keyof typeof OperationStep];


export const OperationStep = {
  storage: 'storage',
  worktree: 'worktree',
  sandbox: 'sandbox',
  node: 'node',
  ready: 'ready',
  quiesce: 'quiesce',
  terminate: 'terminate',
  cleanup: 'cleanup',
  storage_delete: 'storage_delete',
  done: 'done',
} as const;

export type WorkspaceDesiredState = typeof WorkspaceDesiredState[keyof typeof WorkspaceDesiredState];


export const WorkspaceDesiredState = {
  running: 'running',
  stopped: 'stopped',
  deleted: 'deleted',
} as const;

export type WorkspaceKind = typeof WorkspaceKind[keyof typeof WorkspaceKind];


export const WorkspaceKind = {
  main: 'main',
  isolated: 'isolated',
} as const;

export type WorkspaceObservedState = typeof WorkspaceObservedState[keyof typeof WorkspaceObservedState];


export const WorkspaceObservedState = {
  provisioning: 'provisioning',
  starting: 'starting',
  ready: 'ready',
  stopping: 'stopping',
  stopped: 'stopped',
  unavailable: 'unavailable',
  deleting: 'deleting',
  deleted: 'deleted',
} as const;

export interface Workspace {
  admissionEpoch: number;
  admissionOpen: boolean;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  desiredState: WorkspaceDesiredState;
  id: string;
  kind: WorkspaceKind;
  observedState: WorkspaceObservedState;
  ownerUserId: string;
  projectId: string;
  runtimeGeneration: number;
  tenantId: string;
  version: number;
}

export type OperationRequestPrevious = {[key: string]: Workspace};

export interface OperationRequest {
  previous?: OperationRequestPrevious;
}

export interface OperationResult {
  resourceId?: string;
}

export interface Operation {
  actorUserId: string;
  /** @nullable */
  controllerEpoch: number | null;
  createdAt: string;
  /** @nullable */
  errorCode: string | null;
  id: string;
  idempotencyKey: string;
  kind: string;
  projectId: string;
  request: OperationRequest;
  requestHash: string;
  result: OperationResult;
  /** @nullable */
  retryAt: string | null;
  state: OperationState;
  step: OperationStep;
  tenantId: string;
  updatedAt: string;
  version: number;
  /** @nullable */
  workspaceId: string | null;
}

export interface Project {
  createdAt: string;
  /** @nullable */
  credentialRefId: string | null;
  defaultBranch: string;
  /** @nullable */
  deletedAt: string | null;
  id: string;
  lifecycle: string;
  name: string;
  ownerUserId: string;
  repositoryUrl: string;
  spaceId: string;
  tenantId: string;
  version: number;
}

export interface Sandbox {
  createdAt: string;
  generation: number;
  id: string;
  observedState: string;
  /** @nullable */
  substrateSandboxId: string | null;
  /** @nullable */
  terminatedAt: string | null;
  version: number;
  workspaceId: string;
}

export interface Storage {
  layoutVersion: number;
  observedState: string;
  projectId: string;
  storageProfile: string;
  /** @nullable */
  substrateStorageId: string | null;
  version: number;
}

export interface Snapshot {
  effects: Effect[];
  nodes: Node[];
  operation: Operation;
  project: ControllerProject;
  sandboxes: Sandbox[];
  storage: Storage;
  workspaces: ControllerWorkspace[];
}

export interface Space {
  /** @nullable */
  archivedAt: string | null;
  createdAt: string;
  createdBy: string;
  description: string;
  id: string;
  name: string;
  slug: string;
  tenantId: string;
  updatedAt: string;
  version: number;
}

export type SpaceEventType = typeof SpaceEventType[keyof typeof SpaceEventType];


export const SpaceEventType = {
  spaceupdated: 'space.updated',
  spacemember_updated: 'space.member_updated',
  projectcreated: 'project.created',
  projectupdated: 'project.updated',
  projectarchived: 'project.archived',
} as const;

export interface SpaceEvent {
  /** @nullable */
  projectId?: string | null;
  spaceId: string;
  type: SpaceEventType;
  version?: number;
}

export interface SpaceListItem {
  /** @nullable */
  archivedAt: string | null;
  createdAt: string;
  createdBy: string;
  description: string;
  id: string;
  name: string;
  role: string;
  slug: string;
  tenantId: string;
  updatedAt: string;
  version: number;
}

export type SpaceMemberRole = typeof SpaceMemberRole[keyof typeof SpaceMemberRole];


export const SpaceMemberRole = {
  owner: 'owner',
  admin: 'admin',
  member: 'member',
} as const;

export interface SpaceMember {
  /** @nullable */
  createdBy: string | null;
  joinedAt: string;
  role: SpaceMemberRole;
  status: string;
  userId: string;
  version: number;
  workspaceId: string;
}

export interface SpaceMemberListItem {
  displayName: string;
  id: string;
  joinedAt: string;
  role: string;
  status: string;
  userId: string;
  version: number;
  workspaceId: string;
}

export interface Tenant {
  id: string;
  name: string;
  role: string;
  status: string;
}

export interface TenantCreated {
  space: Space;
  tenant: Tenant;
}

export interface Ticket {
  actorUserId: string;
  admissionEpoch: number;
  createdAt: string;
  /** @nullable */
  finishedAt: string | null;
  id: string;
  kind: string;
  nodeInstanceId: string;
  state: string;
  tenantId: string;
  version: number;
  workspaceId: string;
}

export interface User {
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  displayName: string;
  id: string;
  status: string;
  version: number;
}

export type WorkspaceListItemDesiredState = typeof WorkspaceListItemDesiredState[keyof typeof WorkspaceListItemDesiredState];


export const WorkspaceListItemDesiredState = {
  running: 'running',
  stopped: 'stopped',
  deleted: 'deleted',
} as const;

export type WorkspaceListItemKind = typeof WorkspaceListItemKind[keyof typeof WorkspaceListItemKind];


export const WorkspaceListItemKind = {
  main: 'main',
  isolated: 'isolated',
} as const;

export type WorkspaceListItemObservedState = typeof WorkspaceListItemObservedState[keyof typeof WorkspaceListItemObservedState];


export const WorkspaceListItemObservedState = {
  provisioning: 'provisioning',
  starting: 'starting',
  ready: 'ready',
  stopping: 'stopping',
  stopped: 'stopped',
  unavailable: 'unavailable',
  deleting: 'deleting',
  deleted: 'deleted',
} as const;

export interface WorkspaceListItem {
  admissionEpoch: number;
  admissionOpen: boolean;
  /**
     * @nullable
     * @pattern ^([0-9a-f]{40}|[0-9a-f]{64})$
     */
  baseCommitId: string | null;
  branchName: string;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  desiredState: WorkspaceListItemDesiredState;
  id: string;
  kind: WorkspaceListItemKind;
  observedState: WorkspaceListItemObservedState;
  ownerUserId: string;
  projectId: string;
  runtimeGeneration: number;
  tenantId: string;
  /** @nullable */
  title: string | null;
  version: number;
}

export type GetApiV1MeTenantsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1MeTenants200 = {
  items: Tenant[];
  nextCursor: string;
};

export type PostApiV1TenantsBody = {
  name: string;
  /**
     * Lowercase, immutable, unique per tenant.
     * @pattern ^[a-z0-9][a-z0-9-]{0,63}$
     */
  slug: string;
};

export type GetApiV1TenantsTidClonesParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidClones200 = {
  items: CloneOperation[];
  nextCursor: string;
};

export type PostApiV1TenantsTidClonesBody = {
  branch: string;
  repository: string;
  requestId: string;
};

export type GetApiV1TenantsTidMembersParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidMembers200 = {
  items: MemberListItem[];
  nextCursor: string;
};

export type PutApiV1TenantsTidMembersUidBodyRole = typeof PutApiV1TenantsTidMembersUidBodyRole[keyof typeof PutApiV1TenantsTidMembersUidBodyRole];


export const PutApiV1TenantsTidMembersUidBodyRole = {
  admin: 'admin',
  member: 'member',
} as const;

export type PutApiV1TenantsTidMembersUidBodyStatus = typeof PutApiV1TenantsTidMembersUidBodyStatus[keyof typeof PutApiV1TenantsTidMembersUidBodyStatus];


export const PutApiV1TenantsTidMembersUidBodyStatus = {
  active: 'active',
  disabled: 'disabled',
} as const;

export type PutApiV1TenantsTidMembersUidBody = {
  role: PutApiV1TenantsTidMembersUidBodyRole;
  status: PutApiV1TenantsTidMembersUidBodyStatus;
  /** @minimum 0 */
  version?: number;
};

export type PostApiV1TenantsTidOperationsOidRetryBody = {
  /** @minimum 0 */
  version: number;
};

export type PostApiV1TenantsTidOperationsOidRetry202 = {
  operation: Operation | AdminOperation;
};

export type GetApiV1TenantsTidProjectsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidProjects200 = {
  items: Project[];
  nextCursor: string;
};

export type PostApiV1TenantsTidProjectsBody = {
  credentialRefId?: string;
  defaultBranch?: string;
  name: string;
  repositoryUrl: string;
};

export type PostApiV1TenantsTidProjects202 = {
  operation: Operation;
  resource: Project;
  workspace: Workspace;
};

export type DeleteApiV1TenantsTidProjectsPidBody = {
  /** @minimum 0 */
  version: number;
};

export type DeleteApiV1TenantsTidProjectsPid202 = {
  operation: Operation;
  resource: Project;
};

export type PatchApiV1TenantsTidProjectsPidBody = {
  name: string;
  /** @minimum 0 */
  version: number;
};

export type GetApiV1TenantsTidProjectsPidWorkspacesParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidProjectsPidWorkspaces200 = {
  items: WorkspaceListItem[];
  nextCursor: string;
};

export type PostApiV1TenantsTidProjectsPidWorkspacesBody = {
  baseRef: string;
  title: string;
};

export type PostApiV1TenantsTidProjectsPidWorkspaces202 = {
  operation: Operation;
  resource: Workspace;
};

export type GetApiV1TenantsTidResourceStatusParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidResourceStatus200 = {
  items: AdminResource[];
  nextCursor: string;
};

export type GetApiV1TenantsTidSpacesParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidSpaces200 = {
  items: SpaceListItem[];
  nextCursor: string;
};

export type PostApiV1TenantsTidSpacesBody = {
  description: string;
  name: string;
  /**
     * Lowercase, immutable, unique per tenant.
     * @pattern ^[a-z0-9][a-z0-9-]{0,63}$
     */
  slug: string;
};

export type DeleteApiV1TenantsTidSpacesSidBody = {
  /** @minimum 0 */
  version: number;
};

export type PatchApiV1TenantsTidSpacesSidBody = {
  description: string;
  name: string;
  /** @minimum 0 */
  version: number;
};

export type GetApiV1TenantsTidSpacesSidMembersParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidSpacesSidMembers200 = {
  items: SpaceMemberListItem[];
  nextCursor: string;
};

export type PutApiV1TenantsTidSpacesSidMembersUidBodyRole = typeof PutApiV1TenantsTidSpacesSidMembersUidBodyRole[keyof typeof PutApiV1TenantsTidSpacesSidMembersUidBodyRole];


export const PutApiV1TenantsTidSpacesSidMembersUidBodyRole = {
  owner: 'owner',
  admin: 'admin',
  member: 'member',
} as const;

export type PutApiV1TenantsTidSpacesSidMembersUidBodyStatus = typeof PutApiV1TenantsTidSpacesSidMembersUidBodyStatus[keyof typeof PutApiV1TenantsTidSpacesSidMembersUidBodyStatus];


export const PutApiV1TenantsTidSpacesSidMembersUidBodyStatus = {
  active: 'active',
  disabled: 'disabled',
} as const;

export type PutApiV1TenantsTidSpacesSidMembersUidBody = {
  role: PutApiV1TenantsTidSpacesSidMembersUidBodyRole;
  status: PutApiV1TenantsTidSpacesSidMembersUidBodyStatus;
  /** @minimum 0 */
  version?: number;
};

export type GetApiV1TenantsTidSpacesSidProjectsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exclusive UUID cursor, ascending stable ordering.
 */
after?: string;
};

export type GetApiV1TenantsTidSpacesSidProjects200 = {
  items: Project[];
  nextCursor: string;
};

export type PostApiV1TenantsTidSpacesSidProjectsBody = {
  credentialRefId?: string;
  defaultBranch?: string;
  name: string;
  repositoryUrl: string;
};

export type PostApiV1TenantsTidSpacesSidProjects202 = {
  operation: Operation;
  resource: Project;
  workspace: Workspace;
};

export type DeleteApiV1TenantsTidWorkspacesWidBody = {
  /** @minimum 0 */
  version: number;
};

export type DeleteApiV1TenantsTidWorkspacesWid202 = {
  operation: Operation;
  resource: Workspace;
};

export type PostApiV1TenantsTidWorkspacesWidAdministrativeStopBody = {
  /** @minimum 0 */
  version: number;
};

export type PostApiV1TenantsTidWorkspacesWidAdministrativeStop202 = {
  operation: AdminOperation;
  resource: AdminResource;
};

export type PostApiV1TenantsTidWorkspacesWidStartBody = {
  /** @minimum 0 */
  version: number;
};

export type PostApiV1TenantsTidWorkspacesWidStart202 = {
  operation: Operation;
  resource: Workspace;
};

export type PostApiV1TenantsTidWorkspacesWidStopBody = {
  /** @minimum 0 */
  version: number;
};

export type PostApiV1TenantsTidWorkspacesWidStop202 = {
  operation: Operation;
  resource: Workspace;
};

export type Health200Status = typeof Health200Status[keyof typeof Health200Status];


export const Health200Status = {
  ok: 'ok',
} as const;

export type Health200 = {
  status: Health200Status;
};

export type PostInternalV1AccessBodyAction = typeof PostInternalV1AccessBodyAction[keyof typeof PostInternalV1AccessBodyAction];


export const PostInternalV1AccessBodyAction = {
  read: 'read',
  execute: 'execute',
} as const;

export type PostInternalV1AccessBody = {
  action: PostInternalV1AccessBodyAction;
  /** @minimum 0 */
  epoch?: number;
  tenantId: string;
  workspaceId: string;
};

export type PostInternalV1AdmissionsBodyAction = typeof PostInternalV1AdmissionsBodyAction[keyof typeof PostInternalV1AdmissionsBodyAction];


export const PostInternalV1AdmissionsBodyAction = {
  read: 'read',
  execute: 'execute',
} as const;

export type PostInternalV1AdmissionsBodyKind = typeof PostInternalV1AdmissionsBodyKind[keyof typeof PostInternalV1AdmissionsBodyKind];


export const PostInternalV1AdmissionsBodyKind = {
  task: 'task',
  interaction: 'interaction',
} as const;

export type PostInternalV1AdmissionsBody = {
  action: PostInternalV1AdmissionsBodyAction;
  /** @minimum 0 */
  epoch: number;
  kind: PostInternalV1AdmissionsBodyKind;
  tenantId: string;
  ticketId: string;
  workspaceId: string;
};

export type PostInternalV1ControllerLeaseAcquireBody = { [key: string]: unknown };

export type PostInternalV1ControllerLeaseReleaseBody = {
  /** @minimum 0 */
  epoch: number;
};

export type PostInternalV1ControllerLeaseRenewBody = {
  /** @minimum 0 */
  epoch: number;
};

export type PostInternalV1NodesIdleBody = {
  /** @minimum 0 */
  admissionEpoch: number;
  idle: boolean;
  operationId: string;
  /** @minimum 0 */
  version: number;
};

export type PostInternalV1NodesRegisterBodyProtocolVersion = typeof PostInternalV1NodesRegisterBodyProtocolVersion[keyof typeof PostInternalV1NodesRegisterBodyProtocolVersion];


export const PostInternalV1NodesRegisterBodyProtocolVersion = {
  NUMBER_1: 1,
} as const;

export type PostInternalV1NodesRegisterBody = {
  protocolVersion: PostInternalV1NodesRegisterBodyProtocolVersion;
};

export type PostInternalV1NodesStatusBodyConnectionState = typeof PostInternalV1NodesStatusBodyConnectionState[keyof typeof PostInternalV1NodesStatusBodyConnectionState];


export const PostInternalV1NodesStatusBodyConnectionState = {
  connected: 'connected',
  disconnected: 'disconnected',
} as const;

export type PostInternalV1NodesStatusBody = {
  connectionState: PostInternalV1NodesStatusBodyConnectionState;
  initialized: boolean;
  /** @minimum 0 */
  version: number;
};

export type PostInternalV1NodesTicketsTicketFinishBody = {
  /** @minimum 0 */
  version: number;
};

export type PostInternalV1OperationsClaimBody = {
  /** @minimum 0 */
  epoch: number;
};

export type PostInternalV1OperationsOidAdvanceBody = {
  /** @minimum 0 */
  epoch: number;
  /** @minimum 0 */
  version: number;
};

export type PostInternalV1OperationsOidDeferBodyErrorCode = typeof PostInternalV1OperationsOidDeferBodyErrorCode[keyof typeof PostInternalV1OperationsOidDeferBodyErrorCode];


export const PostInternalV1OperationsOidDeferBodyErrorCode = {
  substrate_timeout: 'substrate_timeout',
  termination_unconfirmed: 'termination_unconfirmed',
  git_cleanup_failed: 'git_cleanup_failed',
  node_unavailable: 'node_unavailable',
  external_failure: 'external_failure',
} as const;

export type PostInternalV1OperationsOidDeferBodyState = typeof PostInternalV1OperationsOidDeferBodyState[keyof typeof PostInternalV1OperationsOidDeferBodyState];


export const PostInternalV1OperationsOidDeferBodyState = {
  blocked: 'blocked',
  retry_wait: 'retry_wait',
} as const;

export type PostInternalV1OperationsOidDeferBody = {
  /** @minimum 0 */
  epoch: number;
  errorCode: PostInternalV1OperationsOidDeferBodyErrorCode;
  /**
     * @minimum 1
     * @maximum 3600
     */
  retrySeconds: number;
  state: PostInternalV1OperationsOidDeferBodyState;
  /** @minimum 0 */
  version: number;
};

export type PostInternalV1OperationsOidEffectsBodyKind = typeof PostInternalV1OperationsOidEffectsBodyKind[keyof typeof PostInternalV1OperationsOidEffectsBodyKind];


export const PostInternalV1OperationsOidEffectsBodyKind = {
  storage_ensure: 'storage_ensure',
  worktree_ensure: 'worktree_ensure',
  sandbox_ensure: 'sandbox_ensure',
  sandbox_terminate: 'sandbox_terminate',
  worktree_delete: 'worktree_delete',
  storage_delete: 'storage_delete',
} as const;

export type PostInternalV1OperationsOidEffectsBody = {
  /** @minimum 0 */
  epoch: number;
  kind: PostInternalV1OperationsOidEffectsBodyKind;
  /** @minimum 0 */
  version: number;
  workspaceId?: string;
};

export type PostInternalV1OperationsOidEffects200 = {
  effect: Effect;
  operation: Operation;
};

export type PostInternalV1OperationsOidEffectsEidResultBodyState = typeof PostInternalV1OperationsOidEffectsEidResultBodyState[keyof typeof PostInternalV1OperationsOidEffectsEidResultBodyState];


export const PostInternalV1OperationsOidEffectsEidResultBodyState = {
  running: 'running',
  succeeded: 'succeeded',
  failed: 'failed',
  absent: 'absent',
} as const;

export type PostInternalV1OperationsOidEffectsEidResultBody = {
  /** @minimum 0 */
  epoch: number;
  externalId?: string;
  result: EffectResult;
  state: PostInternalV1OperationsOidEffectsEidResultBodyState;
  /** @minimum 0 */
  version: number;
};

export type PostInternalV1OperationsOidEffectsEidResult200 = {
  effect: Effect;
  operation: Operation;
};

export type PostInternalV1OperationsOidSnapshotBody = {
  /** @minimum 0 */
  epoch: number;
  /** @minimum 0 */
  version: number;
};

