/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV1TenantsTidWorkflowsWfidBody,
  Error,
  GetApiV1TenantsTidWorkflows200,
  GetApiV1TenantsTidWorkflowsParams,
  GetApiV1TenantsTidWorkflowsWfidRuns200,
  GetApiV1TenantsTidWorkflowsWfidRunsParams,
  GetApiV1TenantsTidWorkflowsWfidSnapshots200,
  GetApiV1TenantsTidWorkflowsWfidSnapshotsParams,
  PostApiV1TenantsTidWorkflows200,
  PostApiV1TenantsTidWorkflowsBody,
  PostApiV1TenantsTidWorkflowsWfidPublish200,
  PostApiV1TenantsTidWorkflowsWfidPublishBody,
  PostApiV1TenantsTidWorkflowsWfidRuns200,
  PostApiV1TenantsTidWorkflowsWfidRunsBody,
  PutApiV1TenantsTidWorkflowsWfidBody,
  PutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreBody,
  Workflow,
  WorkflowRun,
  WorkflowSnapshot
} from '../generated.schemas';

import { customInstance } from '../../lib/api-client';
import type { ErrorType } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Workflows are tenant-owned graph documents. `graph` is the authored document (nodes, edges, viewport, editor annotations, global variables), stored and returned whole — the editor is its only reader, so no field inside it is validated or indexed here. A live workflow name is unique per tenant; archiving one frees its name. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/workflows
 */
export const getApiV1TenantsTidWorkflows = (
    tid: string,
    params?: GetApiV1TenantsTidWorkflowsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1TenantsTidWorkflows200>(
      {url: `/api/v1/tenants/${tid}/workflows`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1TenantsTidWorkflowsQueryKey = (tid: string,
    params?: GetApiV1TenantsTidWorkflowsParams,) => {
    return [
    `/api/v1/tenants/${tid}/workflows`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1TenantsTidWorkflowsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>, TError = ErrorType<Error>>(tid: string,
    params?: GetApiV1TenantsTidWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidWorkflowsQueryKey(tid,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>> = ({ signal }) => getApiV1TenantsTidWorkflows(tid,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidWorkflowsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>>
export type GetApiV1TenantsTidWorkflowsQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidWorkflows<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>, TError = ErrorType<Error>>(
 tid: string,
    params: undefined |  GetApiV1TenantsTidWorkflowsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkflows<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkflows<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/workflows
 */

export function useGetApiV1TenantsTidWorkflows<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflows>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidWorkflowsQueryOptions(tid,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Workflows are tenant-owned graph documents. `graph` is the authored document (nodes, edges, viewport, editor annotations, global variables), stored and returned whole — the editor is its only reader, so no field inside it is validated or indexed here. A live workflow name is unique per tenant; archiving one frees its name. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/workflows
 */
export const postApiV1TenantsTidWorkflows = (
    tid: string,
    postApiV1TenantsTidWorkflowsBody: PostApiV1TenantsTidWorkflowsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostApiV1TenantsTidWorkflows200>(
      {url: `/api/v1/tenants/${tid}/workflows`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidWorkflowsBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidWorkflowsMutationKey = () => ['postApiV1TenantsTidWorkflows'] as const;

export const getPostApiV1TenantsTidWorkflowsMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkflows>>, TError,PostApiV1TenantsTidWorkflowsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkflows>>, TError,PostApiV1TenantsTidWorkflowsMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidWorkflowsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidWorkflows>>, PostApiV1TenantsTidWorkflowsMutationVariables> = (props) => {
          const {tid,data} = props ?? {};

          return  postApiV1TenantsTidWorkflows(tid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidWorkflowsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidWorkflows>>>
    export type PostApiV1TenantsTidWorkflowsMutationBody = PostApiV1TenantsTidWorkflowsBody
    export type PostApiV1TenantsTidWorkflowsMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidWorkflowsMutationVariables = {tid: string;data: PostApiV1TenantsTidWorkflowsBody}

    /**
 * @summary POST /api/v1/tenants/:tid/workflows
 */
export const usePostApiV1TenantsTidWorkflows = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkflows>>, TError,PostApiV1TenantsTidWorkflowsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidWorkflows>>,
        TError,
        PostApiV1TenantsTidWorkflowsMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidWorkflowsMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Workflows are tenant-owned graph documents. `graph` is the authored document (nodes, edges, viewport, editor annotations, global variables), stored and returned whole — the editor is its only reader, so no field inside it is validated or indexed here. A live workflow name is unique per tenant; archiving one frees its name. Requires matching resource version and no active project operation. Atomically closes new execution admission. Active tickets return 409 resource_in_use without changing admission. Unknown Node activity requires later proof and remains pending/blocked. main Workspace cannot be independently deleted. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary DELETE /api/v1/tenants/:tid/workflows/:wfid
 */
export const deleteApiV1TenantsTidWorkflowsWfid = (
    tid: string,
    wfid: string,
    deleteApiV1TenantsTidWorkflowsWfidBody: DeleteApiV1TenantsTidWorkflowsWfidBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Workflow>(
      {url: `/api/v1/tenants/${tid}/workflows/${wfid}`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteApiV1TenantsTidWorkflowsWfidBody, signal
    },
      options);
    }




export const getDeleteApiV1TenantsTidWorkflowsWfidMutationKey = () => ['deleteApiV1TenantsTidWorkflowsWfid'] as const;

export const getDeleteApiV1TenantsTidWorkflowsWfidMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidWorkflowsWfid>>, TError,DeleteApiV1TenantsTidWorkflowsWfidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidWorkflowsWfid>>, TError,DeleteApiV1TenantsTidWorkflowsWfidMutationVariables, TContext> => {

const mutationKey = getDeleteApiV1TenantsTidWorkflowsWfidMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1TenantsTidWorkflowsWfid>>, DeleteApiV1TenantsTidWorkflowsWfidMutationVariables> = (props) => {
          const {tid,wfid,data} = props ?? {};

          return  deleteApiV1TenantsTidWorkflowsWfid(tid,wfid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1TenantsTidWorkflowsWfidMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1TenantsTidWorkflowsWfid>>>
    export type DeleteApiV1TenantsTidWorkflowsWfidMutationBody = DeleteApiV1TenantsTidWorkflowsWfidBody
    export type DeleteApiV1TenantsTidWorkflowsWfidMutationError = ErrorType<Error>
    export type DeleteApiV1TenantsTidWorkflowsWfidMutationVariables = {tid: string;wfid: string;data: DeleteApiV1TenantsTidWorkflowsWfidBody}

    /**
 * @summary DELETE /api/v1/tenants/:tid/workflows/:wfid
 */
export const useDeleteApiV1TenantsTidWorkflowsWfid = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidWorkflowsWfid>>, TError,DeleteApiV1TenantsTidWorkflowsWfidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1TenantsTidWorkflowsWfid>>,
        TError,
        DeleteApiV1TenantsTidWorkflowsWfidMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiV1TenantsTidWorkflowsWfidMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Workflows are tenant-owned graph documents. `graph` is the authored document (nodes, edges, viewport, editor annotations, global variables), stored and returned whole — the editor is its only reader, so no field inside it is validated or indexed here. A live workflow name is unique per tenant; archiving one frees its name. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/workflows/:wfid
 */
export const getApiV1TenantsTidWorkflowsWfid = (
    tid: string,
    wfid: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Workflow>(
      {url: `/api/v1/tenants/${tid}/workflows/${wfid}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV1TenantsTidWorkflowsWfidQueryKey = (tid: string,
    wfid: string,) => {
    return [
    `/api/v1/tenants/${tid}/workflows/${wfid}`
    ] as const;
    }


export const getGetApiV1TenantsTidWorkflowsWfidQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>, TError = ErrorType<Error>>(tid: string,
    wfid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidWorkflowsWfidQueryKey(tid,wfid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>> = ({ signal }) => getApiV1TenantsTidWorkflowsWfid(tid,wfid, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && wfid !== null && wfid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidWorkflowsWfidQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>>
export type GetApiV1TenantsTidWorkflowsWfidQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidWorkflowsWfid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkflowsWfid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkflowsWfid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/workflows/:wfid
 */

export function useGetApiV1TenantsTidWorkflowsWfid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidWorkflowsWfidQueryOptions(tid,wfid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Workflows are tenant-owned graph documents. `graph` is the authored document (nodes, edges, viewport, editor annotations, global variables), stored and returned whole — the editor is its only reader, so no field inside it is validated or indexed here. A live workflow name is unique per tenant; archiving one frees its name. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary PUT /api/v1/tenants/:tid/workflows/:wfid
 */
export const putApiV1TenantsTidWorkflowsWfid = (
    tid: string,
    wfid: string,
    putApiV1TenantsTidWorkflowsWfidBody: PutApiV1TenantsTidWorkflowsWfidBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Workflow>(
      {url: `/api/v1/tenants/${tid}/workflows/${wfid}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putApiV1TenantsTidWorkflowsWfidBody, signal
    },
      options);
    }




export const getPutApiV1TenantsTidWorkflowsWfidMutationKey = () => ['putApiV1TenantsTidWorkflowsWfid'] as const;

export const getPutApiV1TenantsTidWorkflowsWfidMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1TenantsTidWorkflowsWfid>>, TError,PutApiV1TenantsTidWorkflowsWfidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1TenantsTidWorkflowsWfid>>, TError,PutApiV1TenantsTidWorkflowsWfidMutationVariables, TContext> => {

const mutationKey = getPutApiV1TenantsTidWorkflowsWfidMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1TenantsTidWorkflowsWfid>>, PutApiV1TenantsTidWorkflowsWfidMutationVariables> = (props) => {
          const {tid,wfid,data} = props ?? {};

          return  putApiV1TenantsTidWorkflowsWfid(tid,wfid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1TenantsTidWorkflowsWfidMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1TenantsTidWorkflowsWfid>>>
    export type PutApiV1TenantsTidWorkflowsWfidMutationBody = PutApiV1TenantsTidWorkflowsWfidBody
    export type PutApiV1TenantsTidWorkflowsWfidMutationError = ErrorType<Error>
    export type PutApiV1TenantsTidWorkflowsWfidMutationVariables = {tid: string;wfid: string;data: PutApiV1TenantsTidWorkflowsWfidBody}

    /**
 * @summary PUT /api/v1/tenants/:tid/workflows/:wfid
 */
export const usePutApiV1TenantsTidWorkflowsWfid = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1TenantsTidWorkflowsWfid>>, TError,PutApiV1TenantsTidWorkflowsWfidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1TenantsTidWorkflowsWfid>>,
        TError,
        PutApiV1TenantsTidWorkflowsWfidMutationVariables,
        TContext
      > => {
      return useMutation(getPutApiV1TenantsTidWorkflowsWfidMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Workflows are tenant-owned graph documents. `graph` is the authored document (nodes, edges, viewport, editor annotations, global variables), stored and returned whole — the editor is its only reader, so no field inside it is validated or indexed here. A live workflow name is unique per tenant; archiving one frees its name. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/workflows/:wfid/publish
 */
export const postApiV1TenantsTidWorkflowsWfidPublish = (
    tid: string,
    wfid: string,
    postApiV1TenantsTidWorkflowsWfidPublishBody: PostApiV1TenantsTidWorkflowsWfidPublishBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostApiV1TenantsTidWorkflowsWfidPublish200>(
      {url: `/api/v1/tenants/${tid}/workflows/${wfid}/publish`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidWorkflowsWfidPublishBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidWorkflowsWfidPublishMutationKey = () => ['postApiV1TenantsTidWorkflowsWfidPublish'] as const;

export const getPostApiV1TenantsTidWorkflowsWfidPublishMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkflowsWfidPublish>>, TError,PostApiV1TenantsTidWorkflowsWfidPublishMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkflowsWfidPublish>>, TError,PostApiV1TenantsTidWorkflowsWfidPublishMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidWorkflowsWfidPublishMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidWorkflowsWfidPublish>>, PostApiV1TenantsTidWorkflowsWfidPublishMutationVariables> = (props) => {
          const {tid,wfid,data} = props ?? {};

          return  postApiV1TenantsTidWorkflowsWfidPublish(tid,wfid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidWorkflowsWfidPublishMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidWorkflowsWfidPublish>>>
    export type PostApiV1TenantsTidWorkflowsWfidPublishMutationBody = PostApiV1TenantsTidWorkflowsWfidPublishBody
    export type PostApiV1TenantsTidWorkflowsWfidPublishMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidWorkflowsWfidPublishMutationVariables = {tid: string;wfid: string;data: PostApiV1TenantsTidWorkflowsWfidPublishBody}

    /**
 * @summary POST /api/v1/tenants/:tid/workflows/:wfid/publish
 */
export const usePostApiV1TenantsTidWorkflowsWfidPublish = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkflowsWfidPublish>>, TError,PostApiV1TenantsTidWorkflowsWfidPublishMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidWorkflowsWfidPublish>>,
        TError,
        PostApiV1TenantsTidWorkflowsWfidPublishMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidWorkflowsWfidPublishMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Workflows are tenant-owned graph documents. `graph` is the authored document (nodes, edges, viewport, editor annotations, global variables), stored and returned whole — the editor is its only reader, so no field inside it is validated or indexed here. A live workflow name is unique per tenant; archiving one frees its name. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/workflows/:wfid/runs
 */
export const getApiV1TenantsTidWorkflowsWfidRuns = (
    tid: string,
    wfid: string,
    params?: GetApiV1TenantsTidWorkflowsWfidRunsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1TenantsTidWorkflowsWfidRuns200>(
      {url: `/api/v1/tenants/${tid}/workflows/${wfid}/runs`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1TenantsTidWorkflowsWfidRunsQueryKey = (tid: string,
    wfid: string,
    params?: GetApiV1TenantsTidWorkflowsWfidRunsParams,) => {
    return [
    `/api/v1/tenants/${tid}/workflows/${wfid}/runs`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1TenantsTidWorkflowsWfidRunsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>, TError = ErrorType<Error>>(tid: string,
    wfid: string,
    params?: GetApiV1TenantsTidWorkflowsWfidRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidWorkflowsWfidRunsQueryKey(tid,wfid,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>> = ({ signal }) => getApiV1TenantsTidWorkflowsWfidRuns(tid,wfid,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && wfid !== null && wfid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidWorkflowsWfidRunsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>>
export type GetApiV1TenantsTidWorkflowsWfidRunsQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidWorkflowsWfidRuns<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string,
    params: undefined |  GetApiV1TenantsTidWorkflowsWfidRunsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkflowsWfidRuns<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string,
    params?: GetApiV1TenantsTidWorkflowsWfidRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkflowsWfidRuns<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string,
    params?: GetApiV1TenantsTidWorkflowsWfidRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/workflows/:wfid/runs
 */

export function useGetApiV1TenantsTidWorkflowsWfidRuns<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string,
    params?: GetApiV1TenantsTidWorkflowsWfidRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRuns>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidWorkflowsWfidRunsQueryOptions(tid,wfid,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Workflows are tenant-owned graph documents. `graph` is the authored document (nodes, edges, viewport, editor annotations, global variables), stored and returned whole — the editor is its only reader, so no field inside it is validated or indexed here. A live workflow name is unique per tenant; archiving one frees its name. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/workflows/:wfid/runs
 */
export const postApiV1TenantsTidWorkflowsWfidRuns = (
    tid: string,
    wfid: string,
    postApiV1TenantsTidWorkflowsWfidRunsBody: PostApiV1TenantsTidWorkflowsWfidRunsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostApiV1TenantsTidWorkflowsWfidRuns200>(
      {url: `/api/v1/tenants/${tid}/workflows/${wfid}/runs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidWorkflowsWfidRunsBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidWorkflowsWfidRunsMutationKey = () => ['postApiV1TenantsTidWorkflowsWfidRuns'] as const;

export const getPostApiV1TenantsTidWorkflowsWfidRunsMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkflowsWfidRuns>>, TError,PostApiV1TenantsTidWorkflowsWfidRunsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkflowsWfidRuns>>, TError,PostApiV1TenantsTidWorkflowsWfidRunsMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidWorkflowsWfidRunsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidWorkflowsWfidRuns>>, PostApiV1TenantsTidWorkflowsWfidRunsMutationVariables> = (props) => {
          const {tid,wfid,data} = props ?? {};

          return  postApiV1TenantsTidWorkflowsWfidRuns(tid,wfid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidWorkflowsWfidRunsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidWorkflowsWfidRuns>>>
    export type PostApiV1TenantsTidWorkflowsWfidRunsMutationBody = PostApiV1TenantsTidWorkflowsWfidRunsBody
    export type PostApiV1TenantsTidWorkflowsWfidRunsMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidWorkflowsWfidRunsMutationVariables = {tid: string;wfid: string;data: PostApiV1TenantsTidWorkflowsWfidRunsBody}

    /**
 * @summary POST /api/v1/tenants/:tid/workflows/:wfid/runs
 */
export const usePostApiV1TenantsTidWorkflowsWfidRuns = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkflowsWfidRuns>>, TError,PostApiV1TenantsTidWorkflowsWfidRunsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidWorkflowsWfidRuns>>,
        TError,
        PostApiV1TenantsTidWorkflowsWfidRunsMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidWorkflowsWfidRunsMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Workflows are tenant-owned graph documents. `graph` is the authored document (nodes, edges, viewport, editor annotations, global variables), stored and returned whole — the editor is its only reader, so no field inside it is validated or indexed here. A live workflow name is unique per tenant; archiving one frees its name. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/workflows/:wfid/runs/:rid
 */
export const getApiV1TenantsTidWorkflowsWfidRunsRid = (
    tid: string,
    wfid: string,
    rid: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkflowRun>(
      {url: `/api/v1/tenants/${tid}/workflows/${wfid}/runs/${rid}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV1TenantsTidWorkflowsWfidRunsRidQueryKey = (tid: string,
    wfid: string,
    rid: string,) => {
    return [
    `/api/v1/tenants/${tid}/workflows/${wfid}/runs/${rid}`
    ] as const;
    }


export const getGetApiV1TenantsTidWorkflowsWfidRunsRidQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>, TError = ErrorType<Error>>(tid: string,
    wfid: string,
    rid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidWorkflowsWfidRunsRidQueryKey(tid,wfid,rid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>> = ({ signal }) => getApiV1TenantsTidWorkflowsWfidRunsRid(tid,wfid,rid, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && wfid !== null && wfid !== undefined && rid !== null && rid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidWorkflowsWfidRunsRidQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>>
export type GetApiV1TenantsTidWorkflowsWfidRunsRidQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidWorkflowsWfidRunsRid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string,
    rid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkflowsWfidRunsRid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string,
    rid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkflowsWfidRunsRid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string,
    rid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/workflows/:wfid/runs/:rid
 */

export function useGetApiV1TenantsTidWorkflowsWfidRunsRid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string,
    rid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidRunsRid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidWorkflowsWfidRunsRidQueryOptions(tid,wfid,rid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Workflows are tenant-owned graph documents. `graph` is the authored document (nodes, edges, viewport, editor annotations, global variables), stored and returned whole — the editor is its only reader, so no field inside it is validated or indexed here. A live workflow name is unique per tenant; archiving one frees its name. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/workflows/:wfid/snapshots
 */
export const getApiV1TenantsTidWorkflowsWfidSnapshots = (
    tid: string,
    wfid: string,
    params?: GetApiV1TenantsTidWorkflowsWfidSnapshotsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1TenantsTidWorkflowsWfidSnapshots200>(
      {url: `/api/v1/tenants/${tid}/workflows/${wfid}/snapshots`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1TenantsTidWorkflowsWfidSnapshotsQueryKey = (tid: string,
    wfid: string,
    params?: GetApiV1TenantsTidWorkflowsWfidSnapshotsParams,) => {
    return [
    `/api/v1/tenants/${tid}/workflows/${wfid}/snapshots`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1TenantsTidWorkflowsWfidSnapshotsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>, TError = ErrorType<Error>>(tid: string,
    wfid: string,
    params?: GetApiV1TenantsTidWorkflowsWfidSnapshotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidWorkflowsWfidSnapshotsQueryKey(tid,wfid,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>> = ({ signal }) => getApiV1TenantsTidWorkflowsWfidSnapshots(tid,wfid,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && wfid !== null && wfid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidWorkflowsWfidSnapshotsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>>
export type GetApiV1TenantsTidWorkflowsWfidSnapshotsQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidWorkflowsWfidSnapshots<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string,
    params: undefined |  GetApiV1TenantsTidWorkflowsWfidSnapshotsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkflowsWfidSnapshots<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string,
    params?: GetApiV1TenantsTidWorkflowsWfidSnapshotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkflowsWfidSnapshots<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string,
    params?: GetApiV1TenantsTidWorkflowsWfidSnapshotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/workflows/:wfid/snapshots
 */

export function useGetApiV1TenantsTidWorkflowsWfidSnapshots<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string,
    params?: GetApiV1TenantsTidWorkflowsWfidSnapshotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshots>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidWorkflowsWfidSnapshotsQueryOptions(tid,wfid,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Workflows are tenant-owned graph documents. `graph` is the authored document (nodes, edges, viewport, editor annotations, global variables), stored and returned whole — the editor is its only reader, so no field inside it is validated or indexed here. A live workflow name is unique per tenant; archiving one frees its name. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/workflows/:wfid/snapshots/:snapshotId
 */
export const getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId = (
    tid: string,
    wfid: string,
    snapshotId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkflowSnapshot>(
      {url: `/api/v1/tenants/${tid}/workflows/${wfid}/snapshots/${snapshotId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdQueryKey = (tid: string,
    wfid: string,
    snapshotId: string,) => {
    return [
    `/api/v1/tenants/${tid}/workflows/${wfid}/snapshots/${snapshotId}`
    ] as const;
    }


export const getGetApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>, TError = ErrorType<Error>>(tid: string,
    wfid: string,
    snapshotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdQueryKey(tid,wfid,snapshotId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>> = ({ signal }) => getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId(tid,wfid,snapshotId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && wfid !== null && wfid !== undefined && snapshotId !== null && snapshotId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>>
export type GetApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string,
    snapshotId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string,
    snapshotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string,
    snapshotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/workflows/:wfid/snapshots/:snapshotId
 */

export function useGetApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>, TError = ErrorType<Error>>(
 tid: string,
    wfid: string,
    snapshotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdQueryOptions(tid,wfid,snapshotId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Workflows are tenant-owned graph documents. `graph` is the authored document (nodes, edges, viewport, editor annotations, global variables), stored and returned whole — the editor is its only reader, so no field inside it is validated or indexed here. A live workflow name is unique per tenant; archiving one frees its name. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary PUT /api/v1/tenants/:tid/workflows/:wfid/snapshots/:snapshotId/restore
 */
export const putApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestore = (
    tid: string,
    wfid: string,
    snapshotId: string,
    putApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreBody: PutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Workflow>(
      {url: `/api/v1/tenants/${tid}/workflows/${wfid}/snapshots/${snapshotId}/restore`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreBody, signal
    },
      options);
    }




export const getPutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreMutationKey = () => ['putApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestore'] as const;

export const getPutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestore>>, TError,PutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestore>>, TError,PutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreMutationVariables, TContext> => {

const mutationKey = getPutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestore>>, PutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreMutationVariables> = (props) => {
          const {tid,wfid,snapshotId,data} = props ?? {};

          return  putApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestore(tid,wfid,snapshotId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestore>>>
    export type PutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreMutationBody = PutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreBody
    export type PutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreMutationError = ErrorType<Error>
    export type PutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreMutationVariables = {tid: string;wfid: string;snapshotId: string;data: PutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreBody}

    /**
 * @summary PUT /api/v1/tenants/:tid/workflows/:wfid/snapshots/:snapshotId/restore
 */
export const usePutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestore = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestore>>, TError,PutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestore>>,
        TError,
        PutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreMutationVariables,
        TContext
      > => {
      return useMutation(getPutApiV1TenantsTidWorkflowsWfidSnapshotsSnapshotIdRestoreMutationOptions(options), queryClient);
    }
