package core

import "fmt"

// The A-side Thread command path (controller-integration D3/D5/D6, Thread D3; control actions
// "agent_thread_claim" and "agent_thread_delivered", served to Controllers by
// AgentRunService.ClaimThreadCommands / RecordThreadCommandDelivered).
//
// Ownership (D6 invariant 7): `thread_commands` has exactly one writer class — this file. The
// business layer reaches the table only through the EnqueueThreadCommand seam, inside its own
// transaction, which is what lets the Thread POST commit an entry and its command together. The
// control plane never writes `thread_entries` or `issue_runs`; the business layer never writes
// `thread_commands`.
//
// Identity separation (D-4C-06): `command_id` is generated here (A), `turn_id` is generated by the
// business layer (B) and travels only inside the command body, and `execution_id` is the
// Controller's session execution registered through RecordDispatch. None of the three is derived
// from another, and the Thread `seq` is not part of this contract at all.

// threadCommandKinds is the closed set the thread_commands.kind CHECK enforces. Validating it here
// turns a schema violation into a caller error instead of an aborted transaction whose SQL detail
// must never reach anyone.
var threadCommandKinds = map[string]bool{"submit_user_turn": true, "end_session": true}

// endSessionReasons mirrors the approved EndSessionReason enum minus UNSPECIFIED (Thread D4): the
// three triggers are user click, idle window and cancellation.
var endSessionReasons = map[string]bool{"user_ended": true, "idle_timeout": true, "cancelled": true}

// SubmitUserTurnCommand builds the canonical command object for one appended user turn.
//
// turnID is the Cloud-generated business identity of the turn (Thread D3) and must be the turn_id of
// the thread_entries row the caller writes in the same transaction, so the entry, the command and
// the Node's later echo can be correlated. content is the caller's content blocks, stored verbatim —
// Cloud never rewrites user content (Thread D2, invariant 6).
func SubmitUserTurnCommand(turnID string, content []Object) Object {
	blocks := make([]any, 0, len(content))
	for _, block := range content {
		blocks = append(blocks, block)
	}
	return Object{"kind": "submit_user_turn", "body": Object{"turn": Object{"turn_id": turnID, "content": blocks}}}
}

// EndSessionCommand builds the canonical command object for one Thread-ending request (Thread D4).
//
// reason is the approved trigger the caller observed — the user ending the conversation, the idle
// window expiring, or the run being cancelled — and is the only thing the command carries: the
// Node decides how to shut the session down, and Cloud never sends a shutdown plan. The reason is
// part of the durable command body, so a Controller replaying an undelivered command cannot lose
// why the session is ending.
func EndSessionCommand(reason string) Object {
	return Object{"kind": "end_session", "body": Object{"reason": reason}}
}

// EnqueueThreadCommand persists one Thread command in the caller's transaction and returns its
// A-generated command_id (controller-integration D6 enqueueThreadCommand, Thread D3).
//
// It runs on the *transaction the caller owns: it opens no transaction of its own, performs no HTTP,
// Node, filesystem or network work, and never commits or rolls back. A returned error leaves the
// caller's transaction to roll back, so a failed Thread POST leaves no entry, no state change and no
// command behind.
//
// The stored body is the canonical durable form of the command — {kind, body} where body is
// {turn: {turn_id, content}} for submit_user_turn and {reason} for end_session. The gRPC translation
// layer converts it to the proto message; nothing here knows the wire shape, exactly as the clone
// input/result objects are the durable form and executions.go does the conversion.
//
// Delivery state is deliberately not written: delivered_at / delivered_execution_id stay NULL until
// RecordThreadCommandDelivered registers the hand-off, and created_at is the database's own clock.
// The run id is queued on the caller's transaction, so ThreadCommandAvailable is published only
// after a successful commit (D5) and a rolled-back command can never produce a phantom signal.
func (StoreAgentRunControlPlane) EnqueueThreadCommand(t *transaction, run, command Object) (string, error) {
	runID := run.S("id")
	if !validID(runID) {
		return "", fmt.Errorf("enqueueThreadCommand: a run id is required")
	}
	kind, body := command.S("kind"), command.O("body")
	if !threadCommandKinds[kind] {
		return "", fmt.Errorf("enqueueThreadCommand: unsupported kind %q", kind)
	}
	if len(body) == 0 {
		return "", fmt.Errorf("enqueueThreadCommand: a %s body is required", kind)
	}
	switch kind {
	case "submit_user_turn":
		turn := body.O("turn")
		if !validID(turn.S("turn_id")) {
			return "", fmt.Errorf("enqueueThreadCommand: submit_user_turn requires a turn_id")
		}
		if content := turn["content"]; len(contentObjects(content)) == 0 {
			return "", fmt.Errorf("enqueueThreadCommand: submit_user_turn requires content")
		}
	case "end_session":
		if !endSessionReasons[body.S("reason")] {
			return "", fmt.Errorf("enqueueThreadCommand: %q is not an approved end-session reason", body.S("reason"))
		}
	}
	id := newID()
	t.exec(`INSERT INTO thread_commands(id, run_id, kind, body) VALUES($1,$2,$3,$4)`, id, runID, kind, jsonText(body))
	t.threadRuns = append(t.threadRuns, runID)
	return id, nil
}

// contentObjects normalizes a command body's content list. The seam's own constructor stores []Object
// and a JSON-bodied caller decodes []any of map[string]any; both must be accepted so the two callers
// agree on one shape instead of one of them failing an unexpected type assertion.
func contentObjects(v any) []Object {
	switch blocks := v.(type) {
	case []Object:
		return blocks
	case []any:
		out := make([]Object, 0, len(blocks))
		for _, block := range blocks {
			switch b := block.(type) {
			case Object:
				out = append(out, b)
			case map[string]any:
				out = append(out, Object(b))
			default:
				return nil
			}
		}
		return out
	default:
		return nil
	}
}

// agentThreadClaim lists the Thread commands a Controller may deliver (controller-integration D3
// ClaimThreadCommands): the not-yet-delivered commands grouped by run, ordered by creation within a
// run, each carrying the run's session execution and its target Node.
//
// It is a pure read — it records no epoch and changes nothing — but it still requires the current
// lease epoch, because the caller is about to act on the answer.
//
// The join is what implements D3's "commands of a run whose session execution is not registered yet
// stay in Cloud": a run still in `pending` (StartSession committed, RecordDispatch not yet) has an
// undelivered command but no registered agent_session execution, so it is not listed and the command
// stays durably in Cloud until the session is dispatched. The lateral sub-select picks exactly one
// execution per run (the newest registered session execution) so a run can never multiply its
// commands in the answer.
//
// Delivery is at-least-once: a command stays listed until a delivery is registered, and the Node
// dedupes by command_id (Node protocol D4). Partitioning the command space across workers (G-021) is
// deliberately not solved here; this is the single-worker guarantee.
func agentThreadClaim(t *transaction, r *ControlRequest) Object {
	limit := r.Body.N("limit")
	require(limit >= 1 && limit <= 100, 400, "invalid_limit")
	return Object{"commands": t.list(`
		SELECT tc.id, tc.run_id, tc.kind, tc.body, tc.created_at, ne.execution_id, ne.node_id
		FROM thread_commands tc
		JOIN LATERAL (
		  SELECT execution_id, node_id FROM node_executions
		  WHERE operation_id = tc.run_id AND kind = 'agent_session'
		  ORDER BY created_at DESC, execution_id DESC LIMIT 1
		) ne ON true
		WHERE tc.delivered_at IS NULL
		ORDER BY tc.run_id, tc.created_at, tc.id
		LIMIT $1`, limit)}
}

// agentThreadDelivered registers that one command was handed to the run's Node
// (controller-integration D3 RecordThreadCommandDelivered).
//
// The first registration wins and is never overwritten: a replay by the same execution converges
// idempotently (the Node legitimately re-registers after a lost reply, and the caller's submission
// identity replays the recorded response anyway), while a different execution is a conflict — no
// last-write-wins, which would silently move the delivery to an execution that never received the
// command. The execution must be an agent_session execution of this command's own run, so the
// delivered_execution_id FK cannot become a lie about who received the command.
//
// The registration is one compare-and-set write with a rows-affected check, like every other control
// state change; a 0 here contradicts the read above under the caller's advisory lock, so it is an
// invariant failure that aborts rather than a client error.
func agentThreadDelivered(t *transaction, r *ControlRequest) Object {
	commandID, executionID := r.Body.S("commandId"), r.Body.S("executionId")
	require(validID(commandID) && executionID != "" && len(executionID) <= 200, 400, "invalid_delivery")

	c := t.one("SELECT * FROM thread_commands WHERE id=$1", commandID)
	require(c != nil, 404, "not_found")
	e := t.one("SELECT * FROM node_executions WHERE execution_id=$1", executionID)
	require(e != nil && e.S("kind") == "agent_session" && e.S("operationId") == c.S("runId"), 409, "delivery_conflict")

	if delivered := c.S("deliveredExecutionId"); delivered != "" {
		require(delivered == executionID, 409, "delivery_conflict")
		return Object{}
	}
	if t.execRows(`UPDATE thread_commands SET delivered_at=now(), delivered_execution_id=$2 WHERE id=$1 AND delivered_at IS NULL`, commandID, executionID) != 1 {
		panic(databaseFailure{fmt.Errorf("thread command %s was registered delivered concurrently", commandID)})
	}
	return Object{}
}
