package core

import "fmt"

// The A-side release path of an Agent run's Workspace: the production DeleteRunWorkspace seam and
// the terminal wire that settles the run when the resulting delete_workspace operation succeeds
// (operation D4, IssueRun D3, controller-integration D6; plan §5 Batch 2).
//
// The Run Workspace is Cloud's own object: the approved operation ADR D4 says the IssueRun's
// dispatch transaction creates it and the transaction entering `releasing` creates its
// delete_workspace operation, "由 Cloud 以系统身份发起，不能被公开 API 操作" (the public start/stop/
// delete of a run Workspace answers 404). So there is exactly one writer for each half: the business
// layer declares through this seam, the Controller executes the operation, and the operation's
// terminal state comes back through the AgentRunHooks seam below — the same one-writer-per-table
// split the whole controller integration is built on (D6 invariant 7).
//
// Two properties of the declaration are worth stating explicitly because they are what makes the
// release path safe:
//
//   - Identity. Operation D4 fixes the idempotency identity of both run-Workspace operations as
//     `(issue_run_id, kind)`, generated by Cloud and never taken from a public idempotency key.
//     This file expresses that identity as `(workspace_id, kind)`: `workspaces.issue_run_id` is
//     UNIQUE (0018), so a workspace determines at most one run and the two spellings denote the same
//     set. The literal `issue_run_id` column on `operations` would add a field to the public
//     `Operation` contract (every column of the row is projected into the API response), which is a
//     contract change this slice has no reason to make; the equivalence is recorded in the plan
//     instead. The read-then-insert below is atomic because every Cloud business/control transaction
//     holds the same global advisory lock (Store.transact), exactly as EnqueueExecutionWork's
//     conflict handling relies on.
//
//   - Queueing. `one_project_operation` allows one unfinished operation per Project, and IssueRun D3
//     accepts that a Project's runs "只在建删 Workspace 时排队". A declaration that finds the Project
//     busy therefore fails the caller's transaction rather than committing a releasing run whose
//     delete was never declared: the run stays exactly where it was, and the retry that matters —
//     the Controller replaying the terminal event, or the Cloud-side delivery pass on its next tick —
//     re-runs the whole settlement. IssueRun D5's "不释放" invariant holds at every commit.

// DeleteRunWorkspace declares the run Workspace's delete_workspace operation in the caller's
// transaction (IssueRun D3, operation D4, controller-integration D6).
//
// It runs only on the caller-owned *transaction, inside which the declaring transition
// (`releasing`) must commit or roll back with it, and it never executes anything: the Controller
// claims and drives the operation, and the run reaches `done` only when that operation's terminal
// state is taken over. Preconditions, all re-read from authoritative rows rather than taken from the
// caller Object: the run exists, is an Agent run, is already `releasing`, and the named Workspace is
// bound to it. A replay (the operation already exists for this Workspace) is an idempotent no-op;
// anything else is an error that rolls the caller's transaction back.
func (StoreAgentRunControlPlane) DeleteRunWorkspace(t *transaction, run Object) error {
	runID, tenantID, wid := run.S("id"), run.S("tenantId"), run.S("workspaceId")
	if !validID(runID) || !validID(tenantID) || !validID(wid) {
		return fmt.Errorf("deleteRunWorkspace: run identity (id/tenantId/workspaceId) is required (got id=%q tenant=%q workspace=%q)", runID, tenantID, wid)
	}
	o := t.one("SELECT * FROM issue_runs WHERE id=$1 AND tenant_id=$2 AND deleted_at IS NULL", runID, tenantID)
	if o == nil {
		return fmt.Errorf("deleteRunWorkspace: issue_run %s not found in tenant %s", runID, tenantID)
	}
	if o.S("executorType") != "agent" {
		return fmt.Errorf("deleteRunWorkspace: run %s is executor_type=%q, not agent", runID, o.S("executorType"))
	}
	// The run Workspace is released only from `releasing` (IssueRun D3/D5, invariant 3). Requiring
	// the phase here means a caller that declared the delete before the run had finished delivering
	// cannot delete a Workspace an Agent session or the delivered objects still depend on.
	if o.S("phase") != "releasing" {
		return fmt.Errorf("deleteRunWorkspace: run %s is phase=%q, not releasing", runID, o.S("phase"))
	}
	// The Workspace row is read without the soft-delete filter: a run Workspace that was already
	// deleted still carries the binding this identity is defined on, and the operation's composite
	// FK (workspace_id, project_id) still holds for it.
	w := t.one("SELECT * FROM workspaces WHERE id=$1 AND issue_run_id=$2", wid, runID)
	if w == nil {
		return fmt.Errorf("deleteRunWorkspace: workspace %s is not bound to run %s", wid, runID)
	}
	// Idempotent replay: this Workspace's delete is already declared and still in flight, so a retried
	// settlement must not create a second operation (IssueRun D3 "每个阶段转换都在接管上一阶段证据的
	// 同一事务中写入"). Only unfinished operations count. A `failed` one is not a declaration that
	// still exists: a Node that refuses to quiesce fails the operation and restores the Workspace
	// (operation D4 "quiesce 失败并按原规则重试"), and the durable intent — the run is `releasing`, so
	// its Workspace must go — has to be re-declarable, or that refusal would strand the run in
	// `releasing` forever. A `succeeded` one cannot be re-declared either way: the same transaction
	// that succeeded it moved the run to `done`, which the phase precondition above already refuses.
	if t.one(`SELECT id FROM operations WHERE workspace_id=$1 AND kind='delete_workspace'
		AND state IN ('queued','running','retry_wait','blocked')`, wid) != nil {
		return nil
	}
	// Queue behind the Project's single operation slot. This is the retryable case IssueRun D3
	// describes; it is an error here so the caller's transaction rolls back instead of committing a
	// releasing run with no delete intent.
	if projectBusy(t, w.S("projectId")) {
		return fmt.Errorf("deleteRunWorkspace: project %s already has an operation in flight; run %s keeps releasing and the delete is declared on retry", w.S("projectId"), runID)
	}
	// The actor is the Workspace owner — the user whose run this is (IssueRun D2: the run Workspace's
	// owner is the triggering user, and the Agent's git identity is that user's). operations.actor_user_id
	// is NOT NULL with a tenant-membership FK; Cloud is the actor "以系统身份", so the only honest
	// human identity is the one the Workspace was created for.
	actor := w.S("ownerUserId")
	if actor == "" || t.one("SELECT user_id FROM tenant_memberships WHERE tenant_id=$1 AND user_id=$2", tenantID, actor) == nil {
		return fmt.Errorf("deleteRunWorkspace: run %s workspace %s has no tenant member owner to act as", runID, wid)
	}
	// request.previous is the pre-transition Workspace snapshot the shared stop/delete path restores
	// from when a Node refuses to quiesce (nodeIdle → restoreAdmission), so a run Workspace refused
	// by its Node behaves exactly like a user Workspace: the operation fails and the state returns.
	//
	// It is stored through stripAgentRunSkeleton for the same reason the public stop/delete path
	// stores it that way: `operations.request` is projected verbatim into the public Operation
	// contract, and the migration-0018 agent columns are deliberately not part of the published
	// workspace shape. The three fields restoreAdmission reads — desiredState, observedState and
	// admissionOpen — are exactly the ones the strip leaves in place.
	req := Object{"previous": Object{w.S("id"): stripAgentRunSkeleton(w)}}
	id := newID()
	t.exec(`INSERT INTO operations(id,tenant_id,actor_user_id,project_id,workspace_id,kind,state,step,request,idempotency_key,request_hash)
		VALUES($1,$2,$3,$4,$5,'delete_workspace','queued','quiesce',$6,$7,$8)`,
		id, tenantID, actor, w.S("projectId"), wid, jsonText(req), "agent-run:"+runID+":delete_workspace",
		requestHash("POST", "/agent-runs/"+runID+"/delete-workspace", req))
	// Admission closes with the declaration, not with the operation's first step: after the releasing
	// transition nothing may start work in this Workspace again, and the epoch bump fences anything
	// that still tries.
	closeAdmission(t, w, "deleted")
	t.queued = append(t.queued, id)
	return nil
}

// runWorkspaceForOperation resolves the IssueRun a run-Workspace operation belongs to, through the
// unique workspaces.issue_run_id binding. It deliberately does not filter on the workspace's
// soft-delete: a delete_workspace operation reaches its terminal state only after the cleanup step
// soft-deleted the Workspace, so the binding must still resolve then. A nil result means the
// operation is not a run-Workspace operation at all.
func runWorkspaceForOperation(t *transaction, wid string) Object {
	if !validID(wid) {
		return nil
	}
	return t.one(`SELECT r.id, r.tenant_id FROM workspaces w JOIN issue_runs r ON r.id = w.issue_run_id
		WHERE w.id=$1 AND r.deleted_at IS NULL`, wid)
}

// agentRunWorkspaceDeleteOp reports whether o is the delete_workspace operation of an Agent run
// Workspace — the only delete operation whose terminal state settles a run. The identity is the
// workspace→run binding, and the predicate is deliberately disjoint from agentRunWorkspaceOp
// (create_workspace): the create path settles `provisioning`, the delete path settles `releasing`.
func agentRunWorkspaceDeleteOp(t *transaction, o Object) bool {
	return o.S("kind") == "delete_workspace" && runWorkspaceForOperation(t, o.S("workspaceId")) != nil
}

// settleRunWorkspaceDeleted is the terminal A→B hook invocation for a run Workspace's delete. It
// runs inside the caller-owned delete_workspace transaction, after the operation has been written
// state='succeeded', and moves the run to `done` through the AgentRunHooks seam. A hook error panics
// databaseFailure so the enclosing transaction rolls back the terminal write too: the operation can
// never commit succeeded while its run stays releasing (mandate §14/§17, plan §5). The run is looked
// up through the workspace→run binding, never taken from caller input.
func settleRunWorkspaceDeleted(t *transaction, o Object) {
	run := runWorkspaceForOperation(t, o.S("workspaceId"))
	if run == nil {
		return
	}
	h := t.hooks
	if h == nil {
		h = UnavailableAgentRunHooks{} // nil-safe fail closed: no business transition without a wired hook
	}
	if err := h.RunWorkspaceDeleted(t, Object{"id": run.S("id"), "tenantId": run.S("tenantId")}); err != nil {
		panic(databaseFailure{err})
	}
}
