/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type AccessAllowedAction = typeof AccessAllowedAction[keyof typeof AccessAllowedAction];


export const AccessAllowedAction = {
  read: 'read',
  execute: 'execute',
} as const;
