/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { AccessAllowedAction } from './accessAllowedAction';

export interface Access {
  allowedAction: AccessAllowedAction;
  executable: boolean;
  runtimeGeneration: number;
  tenantId: string;
  userId: string;
  workspaceId: string;
}
