/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type AdminResourceObservedState = typeof AdminResourceObservedState[keyof typeof AdminResourceObservedState];


export const AdminResourceObservedState = {
  provisioning: 'provisioning',
  starting: 'starting',
  ready: 'ready',
  stopping: 'stopping',
  stopped: 'stopped',
  unavailable: 'unavailable',
  deleting: 'deleting',
  deleted: 'deleted',
} as const;
