/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type AdminResourceDesiredState = typeof AdminResourceDesiredState[keyof typeof AdminResourceDesiredState];


export const AdminResourceDesiredState = {
  running: 'running',
  stopped: 'stopped',
  deleted: 'deleted',
} as const;
