/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export interface AdminOperation {
  createdAt: string;
  id: string;
  kind: string;
  projectId: string;
  state: string;
  step: string;
  tenantId: string;
  updatedAt: string;
  version: number;
  /** @nullable */
  workspaceId: string | null;
}
