/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminResourceDesiredState } from './adminResourceDesiredState';
import type { AdminResourceKind } from './adminResourceKind';
import type { AdminResourceObservedState } from './adminResourceObservedState';

export interface AdminResource {
  desiredState: AdminResourceDesiredState;
  id: string;
  kind: AdminResourceKind;
  observedState: AdminResourceObservedState;
  ownerUserId: string;
  projectId: string;
  runtimeGeneration: number;
  version: number;
}
