/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export interface ControllerWorkspace {
  admissionEpoch: number;
  admissionOpen: boolean;
  /**
     * @nullable
     * @pattern ^([0-9a-f]{40}|[0-9a-f]{64})$
     */
  baseCommitId: string | null;
  branchName: string;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  desiredState: string;
  id: string;
  kind: string;
  observedState: string;
  ownerUserId: string;
  projectId: string;
  relativePath: string;
  requestedRef: string;
  runtimeGeneration: number;
  tenantId: string;
  version: number;
}
