/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { Operation } from './operation';
import type { Project } from './project';

export type DeleteApiV1TenantsTidProjectsPid202 = {
  operation: Operation;
  resource: Project;
};
