/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { EffectRequest } from './effectRequest';
import type { EffectResult } from './effectResult';

export interface Effect {
  createdAt: string;
  /** @nullable */
  externalId: string | null;
  id: string;
  kind: string;
  operationId: string;
  projectId: string;
  reconciledEpoch: number;
  request: EffectRequest;
  result: EffectResult;
  state: string;
  version: number;
  /** @nullable */
  workspaceId: string | null;
}
