/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export interface EffectResult {
  /** @pattern ^([0-9a-f]{40}|[0-9a-f]{64})$ */
  commitId?: string;
  jobTerminated?: boolean;
  layoutVersion?: number;
  nodeId?: string;
  removed?: boolean;
  sandboxInstanceId?: string;
  terminated?: boolean;
}
