/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { EffectRequestKind } from './effectRequestKind';

export interface EffectRequest {
  kind: EffectRequestKind;
  projectId: string;
  repositoryUrl?: string;
  requestedRef?: string;
  sandboxInstanceId?: string;
  workspaceId?: string;
}
