/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type EmptyClaimOperation = typeof EmptyClaimOperation[keyof typeof EmptyClaimOperation] | null;


export const EmptyClaimOperation = {
} as const;
