/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { Tenant } from './tenant';

export type GetApiV1MeTenants200 = {
  items: Tenant[];
  nextCursor: string;
};
