/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { Project } from './project';

export type GetApiV1TenantsTidProjects200 = {
  items: Project[];
  nextCursor: string;
};
