/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { MemberListItem } from './memberListItem';

export type GetApiV1TenantsTidMembers200 = {
  items: MemberListItem[];
  nextCursor: string;
};
