/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminResource } from './adminResource';

export type GetApiV1TenantsTidResourceStatus200 = {
  items: AdminResource[];
  nextCursor: string;
};
