/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type Health200Status = typeof Health200Status[keyof typeof Health200Status];


export const Health200Status = {
  ok: 'ok',
} as const;
