/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type IdleRefusalErrorCode = typeof IdleRefusalErrorCode[keyof typeof IdleRefusalErrorCode];


export const IdleRefusalErrorCode = {
  resource_in_use: 'resource_in_use',
} as const;
