/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { IdleRefusalErrorCode } from './idleRefusalErrorCode';

export interface IdleRefusal {
  accepted: boolean;
  errorCode: IdleRefusalErrorCode;
}
