/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export interface Node {
  connectionState: string;
  /** @nullable */
  endedAt: string | null;
  id: string;
  /** @nullable */
  idleAdmissionEpoch: number | null;
  initialized: boolean;
  lastSeenAt: string;
  protocolVersion: number;
  sandboxInstanceId: string;
  serviceSubject: string;
  version: number;
  workspaceId: string;
}
