/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type OperationStep = typeof OperationStep[keyof typeof OperationStep];


export const OperationStep = {
  storage: 'storage',
  worktree: 'worktree',
  sandbox: 'sandbox',
  node: 'node',
  ready: 'ready',
  quiesce: 'quiesce',
  terminate: 'terminate',
  cleanup: 'cleanup',
  storage_delete: 'storage_delete',
  done: 'done',
} as const;
