/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type OperationState = typeof OperationState[keyof typeof OperationState];


export const OperationState = {
  queued: 'queued',
  running: 'running',
  retry_wait: 'retry_wait',
  blocked: 'blocked',
  succeeded: 'succeeded',
  failed: 'failed',
} as const;
