/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { OperationRequest } from './operationRequest';
import type { OperationResult } from './operationResult';
import type { OperationState } from './operationState';
import type { OperationStep } from './operationStep';

export interface Operation {
  actorUserId: string;
  /** @nullable */
  controllerEpoch: number | null;
  createdAt: string;
  /** @nullable */
  errorCode: string | null;
  id: string;
  idempotencyKey: string;
  kind: string;
  projectId: string;
  request: OperationRequest;
  requestHash: string;
  result: OperationResult;
  /** @nullable */
  retryAt: string | null;
  state: OperationState;
  step: OperationStep;
  tenantId: string;
  updatedAt: string;
  version: number;
  /** @nullable */
  workspaceId: string | null;
}
