/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type PostInternalV1AccessBodyAction = typeof PostInternalV1AccessBodyAction[keyof typeof PostInternalV1AccessBodyAction];


export const PostInternalV1AccessBodyAction = {
  read: 'read',
  execute: 'execute',
} as const;
