/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type PostInternalV1AdmissionsBodyKind = typeof PostInternalV1AdmissionsBodyKind[keyof typeof PostInternalV1AdmissionsBodyKind];


export const PostInternalV1AdmissionsBodyKind = {
  task: 'task',
  interaction: 'interaction',
} as const;
