/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { Effect } from './effect';
import type { Operation } from './operation';

export type PostInternalV1OperationsOidEffectsEidResult200 = {
  effect: Effect;
  operation: Operation;
};
