/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type PostInternalV1AdmissionsBodyAction = typeof PostInternalV1AdmissionsBodyAction[keyof typeof PostInternalV1AdmissionsBodyAction];


export const PostInternalV1AdmissionsBodyAction = {
  read: 'read',
  execute: 'execute',
} as const;
