/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { PostInternalV1OperationsOidEffectsBodyKind } from './postInternalV1OperationsOidEffectsBodyKind';

export type PostInternalV1OperationsOidEffectsBody = {
  /** @minimum 0 */
  epoch: number;
  kind: PostInternalV1OperationsOidEffectsBodyKind;
  /** @minimum 0 */
  version: number;
  workspaceId?: string;
};
