/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { PostInternalV1AdmissionsBodyAction } from './postInternalV1AdmissionsBodyAction';
import type { PostInternalV1AdmissionsBodyKind } from './postInternalV1AdmissionsBodyKind';

export type PostInternalV1AdmissionsBody = {
  action: PostInternalV1AdmissionsBodyAction;
  /** @minimum 0 */
  epoch: number;
  kind: PostInternalV1AdmissionsBodyKind;
  tenantId: string;
  ticketId: string;
  workspaceId: string;
};
