/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { PostInternalV1NodesStatusBodyConnectionState } from './postInternalV1NodesStatusBodyConnectionState';

export type PostInternalV1NodesStatusBody = {
  connectionState: PostInternalV1NodesStatusBodyConnectionState;
  initialized: boolean;
  /** @minimum 0 */
  version: number;
};
