/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type PostInternalV1OperationsOidDeferBodyErrorCode = typeof PostInternalV1OperationsOidDeferBodyErrorCode[keyof typeof PostInternalV1OperationsOidDeferBodyErrorCode];


export const PostInternalV1OperationsOidDeferBodyErrorCode = {
  substrate_timeout: 'substrate_timeout',
  termination_unconfirmed: 'termination_unconfirmed',
  git_cleanup_failed: 'git_cleanup_failed',
  node_unavailable: 'node_unavailable',
  external_failure: 'external_failure',
} as const;
