/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { EffectResult } from './effectResult';
import type { PostInternalV1OperationsOidEffectsEidResultBodyState } from './postInternalV1OperationsOidEffectsEidResultBodyState';

export type PostInternalV1OperationsOidEffectsEidResultBody = {
  /** @minimum 0 */
  epoch: number;
  externalId?: string;
  result: EffectResult;
  state: PostInternalV1OperationsOidEffectsEidResultBodyState;
  /** @minimum 0 */
  version: number;
};
