/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type PostInternalV1NodesRegisterBodyProtocolVersion = typeof PostInternalV1NodesRegisterBodyProtocolVersion[keyof typeof PostInternalV1NodesRegisterBodyProtocolVersion];


export const PostInternalV1NodesRegisterBodyProtocolVersion = {
  NUMBER_1: 1,
} as const;
