/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { PostInternalV1NodesRegisterBodyProtocolVersion } from './postInternalV1NodesRegisterBodyProtocolVersion';

export type PostInternalV1NodesRegisterBody = {
  protocolVersion: PostInternalV1NodesRegisterBodyProtocolVersion;
};
