/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type PostInternalV1NodesIdleBody = {
  /** @minimum 0 */
  admissionEpoch: number;
  idle: boolean;
  operationId: string;
  /** @minimum 0 */
  version: number;
};
