/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { PostInternalV1AccessBodyAction } from './postInternalV1AccessBodyAction';

export type PostInternalV1AccessBody = {
  action: PostInternalV1AccessBodyAction;
  /** @minimum 0 */
  epoch?: number;
  tenantId: string;
  workspaceId: string;
};
