/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type PostInternalV1OperationsOidEffectsBodyKind = typeof PostInternalV1OperationsOidEffectsBodyKind[keyof typeof PostInternalV1OperationsOidEffectsBodyKind];


export const PostInternalV1OperationsOidEffectsBodyKind = {
  storage_ensure: 'storage_ensure',
  worktree_ensure: 'worktree_ensure',
  sandbox_ensure: 'sandbox_ensure',
  sandbox_terminate: 'sandbox_terminate',
  worktree_delete: 'worktree_delete',
  storage_delete: 'storage_delete',
} as const;
