/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type PostInternalV1OperationsOidDeferBodyState = typeof PostInternalV1OperationsOidDeferBodyState[keyof typeof PostInternalV1OperationsOidDeferBodyState];


export const PostInternalV1OperationsOidDeferBodyState = {
  blocked: 'blocked',
  retry_wait: 'retry_wait',
} as const;
