/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOperation } from './adminOperation';
import type { AdminResource } from './adminResource';

export type PostApiV1TenantsTidWorkspacesWidAdministrativeStop202 = {
  operation: AdminOperation;
  resource: AdminResource;
};
