/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { PostInternalV1OperationsOidDeferBodyErrorCode } from './postInternalV1OperationsOidDeferBodyErrorCode';
import type { PostInternalV1OperationsOidDeferBodyState } from './postInternalV1OperationsOidDeferBodyState';

export type PostInternalV1OperationsOidDeferBody = {
  /** @minimum 0 */
  epoch: number;
  errorCode: PostInternalV1OperationsOidDeferBodyErrorCode;
  /**
     * @minimum 1
     * @maximum 3600
     */
  retrySeconds: number;
  state: PostInternalV1OperationsOidDeferBodyState;
  /** @minimum 0 */
  version: number;
};
