/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type PostInternalV1OperationsOidEffectsEidResultBodyState = typeof PostInternalV1OperationsOidEffectsEidResultBodyState[keyof typeof PostInternalV1OperationsOidEffectsEidResultBodyState];


export const PostInternalV1OperationsOidEffectsEidResultBodyState = {
  running: 'running',
  succeeded: 'succeeded',
  failed: 'failed',
  absent: 'absent',
} as const;
