/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { Operation } from './operation';
import type { Workspace } from './workspace';

export type PostApiV1TenantsTidWorkspacesWidStart202 = {
  operation: Operation;
  resource: Workspace;
};
