/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export interface Project {
  createdAt: string;
  /** @nullable */
  credentialRefId: string | null;
  defaultBranch: string;
  /** @nullable */
  deletedAt: string | null;
  id: string;
  lifecycle: string;
  name: string;
  ownerUserId: string;
  repositoryUrl: string;
  tenantId: string;
  version: number;
}
