/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type PutApiV1TenantsTidMembersUidBodyRole = typeof PutApiV1TenantsTidMembersUidBodyRole[keyof typeof PutApiV1TenantsTidMembersUidBodyRole];


export const PutApiV1TenantsTidMembersUidBodyRole = {
  admin: 'admin',
  member: 'member',
} as const;
