/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export type PutApiV1TenantsTidMembersUidBodyStatus = typeof PutApiV1TenantsTidMembersUidBodyStatus[keyof typeof PutApiV1TenantsTidMembersUidBodyStatus];


export const PutApiV1TenantsTidMembersUidBodyStatus = {
  active: 'active',
  disabled: 'disabled',
} as const;
