/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiV1TenantsTidMembersUidBodyRole } from './putApiV1TenantsTidMembersUidBodyRole';
import type { PutApiV1TenantsTidMembersUidBodyStatus } from './putApiV1TenantsTidMembersUidBodyStatus';

export type PutApiV1TenantsTidMembersUidBody = {
  role: PutApiV1TenantsTidMembersUidBodyRole;
  status: PutApiV1TenantsTidMembersUidBodyStatus;
  /** @minimum 0 */
  version?: number;
};
