/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export interface Sandbox {
  createdAt: string;
  generation: number;
  id: string;
  observedState: string;
  /** @nullable */
  substrateSandboxId: string | null;
  /** @nullable */
  terminatedAt: string | null;
  version: number;
  workspaceId: string;
}
