/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { ControllerProject } from './controllerProject';
import type { ControllerWorkspace } from './controllerWorkspace';
import type { Effect } from './effect';
import type { Node } from './node';
import type { Operation } from './operation';
import type { Sandbox } from './sandbox';
import type { Storage } from './storage';

export interface Snapshot {
  effects: Effect[];
  nodes: Node[];
  operation: Operation;
  project: ControllerProject;
  sandboxes: Sandbox[];
  storage: Storage;
  workspaces: ControllerWorkspace[];
}
