/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */

export interface Storage {
  layoutVersion: number;
  observedState: string;
  projectId: string;
  storageProfile: string;
  /** @nullable */
  substrateStorageId: string | null;
  version: number;
}
