/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { WorkspaceDesiredState } from './workspaceDesiredState';
import type { WorkspaceKind } from './workspaceKind';
import type { WorkspaceObservedState } from './workspaceObservedState';

export interface Workspace {
  admissionEpoch: number;
  admissionOpen: boolean;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  desiredState: WorkspaceDesiredState;
  id: string;
  kind: WorkspaceKind;
  observedState: WorkspaceObservedState;
  ownerUserId: string;
  projectId: string;
  runtimeGeneration: number;
  tenantId: string;
  version: number;
}
