/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import type { WorkspaceListItemDesiredState } from './workspaceListItemDesiredState';
import type { WorkspaceListItemKind } from './workspaceListItemKind';
import type { WorkspaceListItemObservedState } from './workspaceListItemObservedState';

export interface WorkspaceListItem {
  admissionEpoch: number;
  admissionOpen: boolean;
  /**
     * @nullable
     * @pattern ^([0-9a-f]{40}|[0-9a-f]{64})$
     */
  baseCommitId: string | null;
  branchName: string;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  desiredState: WorkspaceListItemDesiredState;
  id: string;
  kind: WorkspaceListItemKind;
  observedState: WorkspaceListItemObservedState;
  ownerUserId: string;
  projectId: string;
  runtimeGeneration: number;
  tenantId: string;
  /** @nullable */
  title: string | null;
  version: number;
}
