// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ora/controller/v1/controller.proto

// Cloud-facing contract of one Controller. Identities are opaque strings the API Server has already
// authorized; there are no tenant, user or membership fields at this boundary by design.

package controllerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloneFailureReason int32

const (
	CloneFailureReason_CLONE_FAILURE_REASON_UNSPECIFIED          CloneFailureReason = 0
	CloneFailureReason_CLONE_FAILURE_REASON_SOURCE_UNAVAILABLE   CloneFailureReason = 1
	CloneFailureReason_CLONE_FAILURE_REASON_BRANCH_NOT_FOUND     CloneFailureReason = 2
	CloneFailureReason_CLONE_FAILURE_REASON_DESTINATION_CONFLICT CloneFailureReason = 3
	CloneFailureReason_CLONE_FAILURE_REASON_OPERATION_FAILED     CloneFailureReason = 4
)

// Enum value maps for CloneFailureReason.
var (
	CloneFailureReason_name = map[int32]string{
		0: "CLONE_FAILURE_REASON_UNSPECIFIED",
		1: "CLONE_FAILURE_REASON_SOURCE_UNAVAILABLE",
		2: "CLONE_FAILURE_REASON_BRANCH_NOT_FOUND",
		3: "CLONE_FAILURE_REASON_DESTINATION_CONFLICT",
		4: "CLONE_FAILURE_REASON_OPERATION_FAILED",
	}
	CloneFailureReason_value = map[string]int32{
		"CLONE_FAILURE_REASON_UNSPECIFIED":          0,
		"CLONE_FAILURE_REASON_SOURCE_UNAVAILABLE":   1,
		"CLONE_FAILURE_REASON_BRANCH_NOT_FOUND":     2,
		"CLONE_FAILURE_REASON_DESTINATION_CONFLICT": 3,
		"CLONE_FAILURE_REASON_OPERATION_FAILED":     4,
	}
)

func (x CloneFailureReason) Enum() *CloneFailureReason {
	p := new(CloneFailureReason)
	*p = x
	return p
}

func (x CloneFailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloneFailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_ora_controller_v1_controller_proto_enumTypes[0].Descriptor()
}

func (CloneFailureReason) Type() protoreflect.EnumType {
	return &file_ora_controller_v1_controller_proto_enumTypes[0]
}

func (x CloneFailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloneFailureReason.Descriptor instead.
func (CloneFailureReason) EnumDescriptor() ([]byte, []int) {
	return file_ora_controller_v1_controller_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// Identity or input conflict with a durable record; retrying the same call cannot succeed.
	ErrorCode_ERROR_CODE_CONFLICT      ErrorCode = 1
	ErrorCode_ERROR_CODE_INVALID_INPUT ErrorCode = 2
	// Persistence is temporarily unavailable; nothing was accepted and the call may be retried.
	ErrorCode_ERROR_CODE_UNAVAILABLE ErrorCode = 3
	ErrorCode_ERROR_CODE_NOT_FOUND   ErrorCode = 4
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_CONFLICT",
		2: "ERROR_CODE_INVALID_INPUT",
		3: "ERROR_CODE_UNAVAILABLE",
		4: "ERROR_CODE_NOT_FOUND",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":   0,
		"ERROR_CODE_CONFLICT":      1,
		"ERROR_CODE_INVALID_INPUT": 2,
		"ERROR_CODE_UNAVAILABLE":   3,
		"ERROR_CODE_NOT_FOUND":     4,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_ora_controller_v1_controller_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_ora_controller_v1_controller_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_ora_controller_v1_controller_proto_rawDescGZIP(), []int{1}
}

type AcceptCloneRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identity chosen by the caller so a lost response can be retried without a second clone.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// HTTPS or SSH repository URL; the target Node and paths belong to Controller deployment.
	Repository    string `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Branch        string `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptCloneRequest) Reset() {
	*x = AcceptCloneRequest{}
	mi := &file_ora_controller_v1_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptCloneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptCloneRequest) ProtoMessage() {}

func (x *AcceptCloneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_controller_v1_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptCloneRequest.ProtoReflect.Descriptor instead.
func (*AcceptCloneRequest) Descriptor() ([]byte, []int) {
	return file_ora_controller_v1_controller_proto_rawDescGZIP(), []int{0}
}

func (x *AcceptCloneRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AcceptCloneRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *AcceptCloneRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type AcceptCloneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptCloneResponse) Reset() {
	*x = AcceptCloneResponse{}
	mi := &file_ora_controller_v1_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptCloneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptCloneResponse) ProtoMessage() {}

func (x *AcceptCloneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_controller_v1_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptCloneResponse.ProtoReflect.Descriptor instead.
func (*AcceptCloneResponse) Descriptor() ([]byte, []int) {
	return file_ora_controller_v1_controller_proto_rawDescGZIP(), []int{1}
}

func (x *AcceptCloneResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AcceptCloneResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *AcceptCloneResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type ListOperationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsRequest) Reset() {
	*x = ListOperationsRequest{}
	mi := &file_ora_controller_v1_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsRequest) ProtoMessage() {}

func (x *ListOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_controller_v1_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsRequest.ProtoReflect.Descriptor instead.
func (*ListOperationsRequest) Descriptor() ([]byte, []int) {
	return file_ora_controller_v1_controller_proto_rawDescGZIP(), []int{2}
}

type ListOperationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*CloneOperation      `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsResponse) Reset() {
	*x = ListOperationsResponse{}
	mi := &file_ora_controller_v1_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsResponse) ProtoMessage() {}

func (x *ListOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_controller_v1_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsResponse.ProtoReflect.Descriptor instead.
func (*ListOperationsResponse) Descriptor() ([]byte, []int) {
	return file_ora_controller_v1_controller_proto_rawDescGZIP(), []int{3}
}

func (x *ListOperationsResponse) GetOperations() []*CloneOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_ora_controller_v1_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_controller_v1_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_ora_controller_v1_controller_proto_rawDescGZIP(), []int{4}
}

func (x *GetOperationRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *CloneOperation        `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_ora_controller_v1_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_controller_v1_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_ora_controller_v1_controller_proto_rawDescGZIP(), []int{5}
}

func (x *GetOperationResponse) GetOperation() *CloneOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

// One accepted clone and its durable state. Paths are Node-local facts, not caller-visible files.
type CloneOperation struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	OperationId string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ExecutionId string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	NodeId      string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Repository  string                 `protobuf:"bytes,4,opt,name=repository,proto3" json:"repository,omitempty"`
	Branch      string                 `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`
	// Types that are valid to be assigned to State:
	//
	//	*CloneOperation_Pending
	//	*CloneOperation_Succeeded
	//	*CloneOperation_Failed
	State         isCloneOperation_State `protobuf_oneof:"state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneOperation) Reset() {
	*x = CloneOperation{}
	mi := &file_ora_controller_v1_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneOperation) ProtoMessage() {}

func (x *CloneOperation) ProtoReflect() protoreflect.Message {
	mi := &file_ora_controller_v1_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneOperation.ProtoReflect.Descriptor instead.
func (*CloneOperation) Descriptor() ([]byte, []int) {
	return file_ora_controller_v1_controller_proto_rawDescGZIP(), []int{6}
}

func (x *CloneOperation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *CloneOperation) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *CloneOperation) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CloneOperation) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *CloneOperation) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *CloneOperation) GetState() isCloneOperation_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *CloneOperation) GetPending() *ClonePending {
	if x != nil {
		if x, ok := x.State.(*CloneOperation_Pending); ok {
			return x.Pending
		}
	}
	return nil
}

func (x *CloneOperation) GetSucceeded() *CloneSucceeded {
	if x != nil {
		if x, ok := x.State.(*CloneOperation_Succeeded); ok {
			return x.Succeeded
		}
	}
	return nil
}

func (x *CloneOperation) GetFailed() *CloneFailed {
	if x != nil {
		if x, ok := x.State.(*CloneOperation_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

type isCloneOperation_State interface {
	isCloneOperation_State()
}

type CloneOperation_Pending struct {
	Pending *ClonePending `protobuf:"bytes,6,opt,name=pending,proto3,oneof"`
}

type CloneOperation_Succeeded struct {
	Succeeded *CloneSucceeded `protobuf:"bytes,7,opt,name=succeeded,proto3,oneof"`
}

type CloneOperation_Failed struct {
	Failed *CloneFailed `protobuf:"bytes,8,opt,name=failed,proto3,oneof"`
}

func (*CloneOperation_Pending) isCloneOperation_State() {}

func (*CloneOperation_Succeeded) isCloneOperation_State() {}

func (*CloneOperation_Failed) isCloneOperation_State() {}

// Accepted with no terminal result yet; makes no claim about whether Git is currently running.
type ClonePending struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClonePending) Reset() {
	*x = ClonePending{}
	mi := &file_ora_controller_v1_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClonePending) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClonePending) ProtoMessage() {}

func (x *ClonePending) ProtoReflect() protoreflect.Message {
	mi := &file_ora_controller_v1_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClonePending.ProtoReflect.Descriptor instead.
func (*ClonePending) Descriptor() ([]byte, []int) {
	return file_ora_controller_v1_controller_proto_rawDescGZIP(), []int{7}
}

type CloneSucceeded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneSucceeded) Reset() {
	*x = CloneSucceeded{}
	mi := &file_ora_controller_v1_controller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneSucceeded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneSucceeded) ProtoMessage() {}

func (x *CloneSucceeded) ProtoReflect() protoreflect.Message {
	mi := &file_ora_controller_v1_controller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneSucceeded.ProtoReflect.Descriptor instead.
func (*CloneSucceeded) Descriptor() ([]byte, []int) {
	return file_ora_controller_v1_controller_proto_rawDescGZIP(), []int{8}
}

func (x *CloneSucceeded) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CloneSucceeded) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

type CloneFailed struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Reason CloneFailureReason     `protobuf:"varint,1,opt,name=reason,proto3,enum=ora.controller.v1.CloneFailureReason" json:"reason,omitempty"`
	// Directory the Node retained for inspection, when it kept one.
	RetainedPath  *string `protobuf:"bytes,2,opt,name=retained_path,json=retainedPath,proto3,oneof" json:"retained_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneFailed) Reset() {
	*x = CloneFailed{}
	mi := &file_ora_controller_v1_controller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneFailed) ProtoMessage() {}

func (x *CloneFailed) ProtoReflect() protoreflect.Message {
	mi := &file_ora_controller_v1_controller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneFailed.ProtoReflect.Descriptor instead.
func (*CloneFailed) Descriptor() ([]byte, []int) {
	return file_ora_controller_v1_controller_proto_rawDescGZIP(), []int{9}
}

func (x *CloneFailed) GetReason() CloneFailureReason {
	if x != nil {
		return x.Reason
	}
	return CloneFailureReason_CLONE_FAILURE_REASON_UNSPECIFIED
}

func (x *CloneFailed) GetRetainedPath() string {
	if x != nil && x.RetainedPath != nil {
		return *x.RetainedPath
	}
	return ""
}

// Classification attached to failed calls as a google.rpc.Status detail, so callers branch on the
// enum rather than on status messages. The gRPC status code carries the same classification.
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=ora.controller.v1.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_ora_controller_v1_controller_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_ora_controller_v1_controller_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_ora_controller_v1_controller_proto_rawDescGZIP(), []int{10}
}

func (x *ErrorDetail) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

var File_ora_controller_v1_controller_proto protoreflect.FileDescriptor

const file_ora_controller_v1_controller_proto_rawDesc = "" +
	"\n" +
	"\"ora/controller/v1/controller.proto\x12\x11ora.controller.v1\"k\n" +
	"\x12AcceptCloneRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\"z\n" +
	"\x13AcceptCloneResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\"\x17\n" +
	"\x15ListOperationsRequest\"[\n" +
	"\x16ListOperationsResponse\x12A\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2!.ora.controller.v1.CloneOperationR\n" +
	"operations\"8\n" +
	"\x13GetOperationRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"W\n" +
	"\x14GetOperationResponse\x12?\n" +
	"\toperation\x18\x01 \x01(\v2!.ora.controller.v1.CloneOperationR\toperation\"\xea\x02\n" +
	"\x0eCloneOperation\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1e\n" +
	"\n" +
	"repository\x18\x04 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06branch\x18\x05 \x01(\tR\x06branch\x12;\n" +
	"\apending\x18\x06 \x01(\v2\x1f.ora.controller.v1.ClonePendingH\x00R\apending\x12A\n" +
	"\tsucceeded\x18\a \x01(\v2!.ora.controller.v1.CloneSucceededH\x00R\tsucceeded\x128\n" +
	"\x06failed\x18\b \x01(\v2\x1e.ora.controller.v1.CloneFailedH\x00R\x06failedB\a\n" +
	"\x05state\"\x0e\n" +
	"\fClonePending\"<\n" +
	"\x0eCloneSucceeded\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\"\x88\x01\n" +
	"\vCloneFailed\x12=\n" +
	"\x06reason\x18\x01 \x01(\x0e2%.ora.controller.v1.CloneFailureReasonR\x06reason\x12(\n" +
	"\rretained_path\x18\x02 \x01(\tH\x00R\fretainedPath\x88\x01\x01B\x10\n" +
	"\x0e_retained_path\"?\n" +
	"\vErrorDetail\x120\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1c.ora.controller.v1.ErrorCodeR\x04code*\xec\x01\n" +
	"\x12CloneFailureReason\x12$\n" +
	" CLONE_FAILURE_REASON_UNSPECIFIED\x10\x00\x12+\n" +
	"'CLONE_FAILURE_REASON_SOURCE_UNAVAILABLE\x10\x01\x12)\n" +
	"%CLONE_FAILURE_REASON_BRANCH_NOT_FOUND\x10\x02\x12-\n" +
	")CLONE_FAILURE_REASON_DESTINATION_CONFLICT\x10\x03\x12)\n" +
	"%CLONE_FAILURE_REASON_OPERATION_FAILED\x10\x04*\x94\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ERROR_CODE_CONFLICT\x10\x01\x12\x1c\n" +
	"\x18ERROR_CODE_INVALID_INPUT\x10\x02\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\x03\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x042\xb9\x02\n" +
	"\x11ControllerService\x12\\\n" +
	"\vAcceptClone\x12%.ora.controller.v1.AcceptCloneRequest\x1a&.ora.controller.v1.AcceptCloneResponse\x12e\n" +
	"\x0eListOperations\x12(.ora.controller.v1.ListOperationsRequest\x1a).ora.controller.v1.ListOperationsResponse\x12_\n" +
	"\fGetOperation\x12&.ora.controller.v1.GetOperationRequest\x1a'.ora.controller.v1.GetOperationResponseB\xd1\x01\n" +
	"\x15com.ora.controller.v1B\x0fControllerProtoP\x01ZAgithub.com/wanglongan587/cloud/internal/controllerpb;controllerpb\xa2\x02\x03OCX\xaa\x02\x11Ora.Controller.V1\xca\x02\x11Ora\\Controller\\V1\xe2\x02\x1dOra\\Controller\\V1\\GPBMetadata\xea\x02\x13Ora::Controller::V1b\x06proto3"

var (
	file_ora_controller_v1_controller_proto_rawDescOnce sync.Once
	file_ora_controller_v1_controller_proto_rawDescData []byte
)

func file_ora_controller_v1_controller_proto_rawDescGZIP() []byte {
	file_ora_controller_v1_controller_proto_rawDescOnce.Do(func() {
		file_ora_controller_v1_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ora_controller_v1_controller_proto_rawDesc), len(file_ora_controller_v1_controller_proto_rawDesc)))
	})
	return file_ora_controller_v1_controller_proto_rawDescData
}

var file_ora_controller_v1_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ora_controller_v1_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_ora_controller_v1_controller_proto_goTypes = []any{
	(CloneFailureReason)(0),        // 0: ora.controller.v1.CloneFailureReason
	(ErrorCode)(0),                 // 1: ora.controller.v1.ErrorCode
	(*AcceptCloneRequest)(nil),     // 2: ora.controller.v1.AcceptCloneRequest
	(*AcceptCloneResponse)(nil),    // 3: ora.controller.v1.AcceptCloneResponse
	(*ListOperationsRequest)(nil),  // 4: ora.controller.v1.ListOperationsRequest
	(*ListOperationsResponse)(nil), // 5: ora.controller.v1.ListOperationsResponse
	(*GetOperationRequest)(nil),    // 6: ora.controller.v1.GetOperationRequest
	(*GetOperationResponse)(nil),   // 7: ora.controller.v1.GetOperationResponse
	(*CloneOperation)(nil),         // 8: ora.controller.v1.CloneOperation
	(*ClonePending)(nil),           // 9: ora.controller.v1.ClonePending
	(*CloneSucceeded)(nil),         // 10: ora.controller.v1.CloneSucceeded
	(*CloneFailed)(nil),            // 11: ora.controller.v1.CloneFailed
	(*ErrorDetail)(nil),            // 12: ora.controller.v1.ErrorDetail
}
var file_ora_controller_v1_controller_proto_depIdxs = []int32{
	8,  // 0: ora.controller.v1.ListOperationsResponse.operations:type_name -> ora.controller.v1.CloneOperation
	8,  // 1: ora.controller.v1.GetOperationResponse.operation:type_name -> ora.controller.v1.CloneOperation
	9,  // 2: ora.controller.v1.CloneOperation.pending:type_name -> ora.controller.v1.ClonePending
	10, // 3: ora.controller.v1.CloneOperation.succeeded:type_name -> ora.controller.v1.CloneSucceeded
	11, // 4: ora.controller.v1.CloneOperation.failed:type_name -> ora.controller.v1.CloneFailed
	0,  // 5: ora.controller.v1.CloneFailed.reason:type_name -> ora.controller.v1.CloneFailureReason
	1,  // 6: ora.controller.v1.ErrorDetail.code:type_name -> ora.controller.v1.ErrorCode
	2,  // 7: ora.controller.v1.ControllerService.AcceptClone:input_type -> ora.controller.v1.AcceptCloneRequest
	4,  // 8: ora.controller.v1.ControllerService.ListOperations:input_type -> ora.controller.v1.ListOperationsRequest
	6,  // 9: ora.controller.v1.ControllerService.GetOperation:input_type -> ora.controller.v1.GetOperationRequest
	3,  // 10: ora.controller.v1.ControllerService.AcceptClone:output_type -> ora.controller.v1.AcceptCloneResponse
	5,  // 11: ora.controller.v1.ControllerService.ListOperations:output_type -> ora.controller.v1.ListOperationsResponse
	7,  // 12: ora.controller.v1.ControllerService.GetOperation:output_type -> ora.controller.v1.GetOperationResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_ora_controller_v1_controller_proto_init() }
func file_ora_controller_v1_controller_proto_init() {
	if File_ora_controller_v1_controller_proto != nil {
		return
	}
	file_ora_controller_v1_controller_proto_msgTypes[6].OneofWrappers = []any{
		(*CloneOperation_Pending)(nil),
		(*CloneOperation_Succeeded)(nil),
		(*CloneOperation_Failed)(nil),
	}
	file_ora_controller_v1_controller_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ora_controller_v1_controller_proto_rawDesc), len(file_ora_controller_v1_controller_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ora_controller_v1_controller_proto_goTypes,
		DependencyIndexes: file_ora_controller_v1_controller_proto_depIdxs,
		EnumInfos:         file_ora_controller_v1_controller_proto_enumTypes,
		MessageInfos:      file_ora_controller_v1_controller_proto_msgTypes,
	}.Build()
	File_ora_controller_v1_controller_proto = out.File
	file_ora_controller_v1_controller_proto_goTypes = nil
	file_ora_controller_v1_controller_proto_depIdxs = nil
}
