/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV1TenantsTidWorkspacesWid202,
  DeleteApiV1TenantsTidWorkspacesWidBody,
  Error,
  GetApiV1TenantsTidProjectsPidWorkspaces200,
  GetApiV1TenantsTidProjectsPidWorkspacesParams,
  GetApiV1TenantsTidWorkspacesWidForceStop200,
  PostApiV1TenantsTidProjectsPidWorkspaces202,
  PostApiV1TenantsTidProjectsPidWorkspacesBody,
  PostApiV1TenantsTidWorkspacesWidControlAcquireBody,
  PostApiV1TenantsTidWorkspacesWidControlReleaseBody,
  PostApiV1TenantsTidWorkspacesWidControlRenewBody,
  PostApiV1TenantsTidWorkspacesWidForceStop202,
  PostApiV1TenantsTidWorkspacesWidForceStopBody,
  PostApiV1TenantsTidWorkspacesWidRestart202,
  PostApiV1TenantsTidWorkspacesWidRestartBody,
  PostApiV1TenantsTidWorkspacesWidStart202,
  PostApiV1TenantsTidWorkspacesWidStartBody,
  PostApiV1TenantsTidWorkspacesWidStop202,
  PostApiV1TenantsTidWorkspacesWidStopBody,
  RuntimeControl,
  Workspace
} from '../generated.schemas';

import { customInstance } from '../../lib/api-client';
import type { ErrorType } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/projects/:pid/workspaces
 */
export const getApiV1TenantsTidProjectsPidWorkspaces = (
    tid: string,
    pid: string,
    params?: GetApiV1TenantsTidProjectsPidWorkspacesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1TenantsTidProjectsPidWorkspaces200>(
      {url: `/api/v1/tenants/${tid}/projects/${pid}/workspaces`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1TenantsTidProjectsPidWorkspacesQueryKey = (tid: string,
    pid: string,
    params?: GetApiV1TenantsTidProjectsPidWorkspacesParams,) => {
    return [
    `/api/v1/tenants/${tid}/projects/${pid}/workspaces`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1TenantsTidProjectsPidWorkspacesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>, TError = ErrorType<Error>>(tid: string,
    pid: string,
    params?: GetApiV1TenantsTidProjectsPidWorkspacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidProjectsPidWorkspacesQueryKey(tid,pid,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>> = ({ signal }) => getApiV1TenantsTidProjectsPidWorkspaces(tid,pid,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && pid !== null && pid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidProjectsPidWorkspacesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>>
export type GetApiV1TenantsTidProjectsPidWorkspacesQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidProjectsPidWorkspaces<TData = Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>, TError = ErrorType<Error>>(
 tid: string,
    pid: string,
    params: undefined |  GetApiV1TenantsTidProjectsPidWorkspacesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidProjectsPidWorkspaces<TData = Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>, TError = ErrorType<Error>>(
 tid: string,
    pid: string,
    params?: GetApiV1TenantsTidProjectsPidWorkspacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidProjectsPidWorkspaces<TData = Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>, TError = ErrorType<Error>>(
 tid: string,
    pid: string,
    params?: GetApiV1TenantsTidProjectsPidWorkspacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/projects/:pid/workspaces
 */

export function useGetApiV1TenantsTidProjectsPidWorkspaces<TData = Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>, TError = ErrorType<Error>>(
 tid: string,
    pid: string,
    params?: GetApiV1TenantsTidProjectsPidWorkspacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPidWorkspaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidProjectsPidWorkspacesQueryOptions(tid,pid,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Creates one isolated Workspace and Task display identity. title/baseRef required; baseRef becomes the Workspace's requestedRef, which its Node clones; HEAD means the Project's defaultBranch. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/projects/:pid/workspaces
 */
export const postApiV1TenantsTidProjectsPidWorkspaces = (
    tid: string,
    pid: string,
    postApiV1TenantsTidProjectsPidWorkspacesBody: PostApiV1TenantsTidProjectsPidWorkspacesBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostApiV1TenantsTidProjectsPidWorkspaces202>(
      {url: `/api/v1/tenants/${tid}/projects/${pid}/workspaces`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidProjectsPidWorkspacesBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidProjectsPidWorkspacesMutationKey = () => ['postApiV1TenantsTidProjectsPidWorkspaces'] as const;

export const getPostApiV1TenantsTidProjectsPidWorkspacesMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidProjectsPidWorkspaces>>, TError,PostApiV1TenantsTidProjectsPidWorkspacesMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidProjectsPidWorkspaces>>, TError,PostApiV1TenantsTidProjectsPidWorkspacesMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidProjectsPidWorkspacesMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidProjectsPidWorkspaces>>, PostApiV1TenantsTidProjectsPidWorkspacesMutationVariables> = (props) => {
          const {tid,pid,data} = props ?? {};

          return  postApiV1TenantsTidProjectsPidWorkspaces(tid,pid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidProjectsPidWorkspacesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidProjectsPidWorkspaces>>>
    export type PostApiV1TenantsTidProjectsPidWorkspacesMutationBody = PostApiV1TenantsTidProjectsPidWorkspacesBody
    export type PostApiV1TenantsTidProjectsPidWorkspacesMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidProjectsPidWorkspacesMutationVariables = {tid: string;pid: string;data: PostApiV1TenantsTidProjectsPidWorkspacesBody}

    /**
 * @summary POST /api/v1/tenants/:tid/projects/:pid/workspaces
 */
export const usePostApiV1TenantsTidProjectsPidWorkspaces = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidProjectsPidWorkspaces>>, TError,PostApiV1TenantsTidProjectsPidWorkspacesMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidProjectsPidWorkspaces>>,
        TError,
        PostApiV1TenantsTidProjectsPidWorkspacesMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidProjectsPidWorkspacesMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Requires matching resource version and no active project operation. Atomically closes new execution admission. Active tickets return 409 resource_in_use without changing admission. Unknown Node activity requires later proof and remains pending/blocked. main Workspace cannot be independently deleted. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary DELETE /api/v1/tenants/:tid/workspaces/:wid
 */
export const deleteApiV1TenantsTidWorkspacesWid = (
    tid: string,
    wid: string,
    deleteApiV1TenantsTidWorkspacesWidBody: DeleteApiV1TenantsTidWorkspacesWidBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DeleteApiV1TenantsTidWorkspacesWid202>(
      {url: `/api/v1/tenants/${tid}/workspaces/${wid}`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteApiV1TenantsTidWorkspacesWidBody, signal
    },
      options);
    }




export const getDeleteApiV1TenantsTidWorkspacesWidMutationKey = () => ['deleteApiV1TenantsTidWorkspacesWid'] as const;

export const getDeleteApiV1TenantsTidWorkspacesWidMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidWorkspacesWid>>, TError,DeleteApiV1TenantsTidWorkspacesWidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidWorkspacesWid>>, TError,DeleteApiV1TenantsTidWorkspacesWidMutationVariables, TContext> => {

const mutationKey = getDeleteApiV1TenantsTidWorkspacesWidMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1TenantsTidWorkspacesWid>>, DeleteApiV1TenantsTidWorkspacesWidMutationVariables> = (props) => {
          const {tid,wid,data} = props ?? {};

          return  deleteApiV1TenantsTidWorkspacesWid(tid,wid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1TenantsTidWorkspacesWidMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1TenantsTidWorkspacesWid>>>
    export type DeleteApiV1TenantsTidWorkspacesWidMutationBody = DeleteApiV1TenantsTidWorkspacesWidBody
    export type DeleteApiV1TenantsTidWorkspacesWidMutationError = ErrorType<Error>
    export type DeleteApiV1TenantsTidWorkspacesWidMutationVariables = {tid: string;wid: string;data: DeleteApiV1TenantsTidWorkspacesWidBody}

    /**
 * @summary DELETE /api/v1/tenants/:tid/workspaces/:wid
 */
export const useDeleteApiV1TenantsTidWorkspacesWid = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidWorkspacesWid>>, TError,DeleteApiV1TenantsTidWorkspacesWidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1TenantsTidWorkspacesWid>>,
        TError,
        DeleteApiV1TenantsTidWorkspacesWidMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiV1TenantsTidWorkspacesWidMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/workspaces/:wid
 */
export const getApiV1TenantsTidWorkspacesWid = (
    tid: string,
    wid: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Workspace>(
      {url: `/api/v1/tenants/${tid}/workspaces/${wid}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV1TenantsTidWorkspacesWidQueryKey = (tid: string,
    wid: string,) => {
    return [
    `/api/v1/tenants/${tid}/workspaces/${wid}`
    ] as const;
    }


export const getGetApiV1TenantsTidWorkspacesWidQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>, TError = ErrorType<Error>>(tid: string,
    wid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidWorkspacesWidQueryKey(tid,wid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>> = ({ signal }) => getApiV1TenantsTidWorkspacesWid(tid,wid, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && wid !== null && wid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidWorkspacesWidQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>>
export type GetApiV1TenantsTidWorkspacesWidQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidWorkspacesWid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>, TError = ErrorType<Error>>(
 tid: string,
    wid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkspacesWid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>, TError = ErrorType<Error>>(
 tid: string,
    wid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkspacesWid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>, TError = ErrorType<Error>>(
 tid: string,
    wid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/workspaces/:wid
 */

export function useGetApiV1TenantsTidWorkspacesWid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>, TError = ErrorType<Error>>(
 tid: string,
    wid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidWorkspacesWidQueryOptions(tid,wid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/workspaces/:wid/control
 */
export const getApiV1TenantsTidWorkspacesWidControl = (
    tid: string,
    wid: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<RuntimeControl>(
      {url: `/api/v1/tenants/${tid}/workspaces/${wid}/control`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV1TenantsTidWorkspacesWidControlQueryKey = (tid: string,
    wid: string,) => {
    return [
    `/api/v1/tenants/${tid}/workspaces/${wid}/control`
    ] as const;
    }


export const getGetApiV1TenantsTidWorkspacesWidControlQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>, TError = ErrorType<Error>>(tid: string,
    wid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidWorkspacesWidControlQueryKey(tid,wid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>> = ({ signal }) => getApiV1TenantsTidWorkspacesWidControl(tid,wid, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && wid !== null && wid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidWorkspacesWidControlQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>>
export type GetApiV1TenantsTidWorkspacesWidControlQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidWorkspacesWidControl<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>, TError = ErrorType<Error>>(
 tid: string,
    wid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkspacesWidControl<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>, TError = ErrorType<Error>>(
 tid: string,
    wid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkspacesWidControl<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>, TError = ErrorType<Error>>(
 tid: string,
    wid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/workspaces/:wid/control
 */

export function useGetApiV1TenantsTidWorkspacesWidControl<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>, TError = ErrorType<Error>>(
 tid: string,
    wid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidControl>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidWorkspacesWidControlQueryOptions(tid,wid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/workspaces/:wid/control/acquire
 */
export const postApiV1TenantsTidWorkspacesWidControlAcquire = (
    tid: string,
    wid: string,
    postApiV1TenantsTidWorkspacesWidControlAcquireBody: PostApiV1TenantsTidWorkspacesWidControlAcquireBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<RuntimeControl>(
      {url: `/api/v1/tenants/${tid}/workspaces/${wid}/control/acquire`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidWorkspacesWidControlAcquireBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidWorkspacesWidControlAcquireMutationKey = () => ['postApiV1TenantsTidWorkspacesWidControlAcquire'] as const;

export const getPostApiV1TenantsTidWorkspacesWidControlAcquireMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlAcquire>>, TError,PostApiV1TenantsTidWorkspacesWidControlAcquireMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlAcquire>>, TError,PostApiV1TenantsTidWorkspacesWidControlAcquireMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidWorkspacesWidControlAcquireMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlAcquire>>, PostApiV1TenantsTidWorkspacesWidControlAcquireMutationVariables> = (props) => {
          const {tid,wid,data} = props ?? {};

          return  postApiV1TenantsTidWorkspacesWidControlAcquire(tid,wid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidWorkspacesWidControlAcquireMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlAcquire>>>
    export type PostApiV1TenantsTidWorkspacesWidControlAcquireMutationBody = PostApiV1TenantsTidWorkspacesWidControlAcquireBody
    export type PostApiV1TenantsTidWorkspacesWidControlAcquireMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidWorkspacesWidControlAcquireMutationVariables = {tid: string;wid: string;data: PostApiV1TenantsTidWorkspacesWidControlAcquireBody}

    /**
 * @summary POST /api/v1/tenants/:tid/workspaces/:wid/control/acquire
 */
export const usePostApiV1TenantsTidWorkspacesWidControlAcquire = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlAcquire>>, TError,PostApiV1TenantsTidWorkspacesWidControlAcquireMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlAcquire>>,
        TError,
        PostApiV1TenantsTidWorkspacesWidControlAcquireMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidWorkspacesWidControlAcquireMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/workspaces/:wid/control/release
 */
export const postApiV1TenantsTidWorkspacesWidControlRelease = (
    tid: string,
    wid: string,
    postApiV1TenantsTidWorkspacesWidControlReleaseBody: PostApiV1TenantsTidWorkspacesWidControlReleaseBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<RuntimeControl>(
      {url: `/api/v1/tenants/${tid}/workspaces/${wid}/control/release`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidWorkspacesWidControlReleaseBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidWorkspacesWidControlReleaseMutationKey = () => ['postApiV1TenantsTidWorkspacesWidControlRelease'] as const;

export const getPostApiV1TenantsTidWorkspacesWidControlReleaseMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlRelease>>, TError,PostApiV1TenantsTidWorkspacesWidControlReleaseMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlRelease>>, TError,PostApiV1TenantsTidWorkspacesWidControlReleaseMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidWorkspacesWidControlReleaseMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlRelease>>, PostApiV1TenantsTidWorkspacesWidControlReleaseMutationVariables> = (props) => {
          const {tid,wid,data} = props ?? {};

          return  postApiV1TenantsTidWorkspacesWidControlRelease(tid,wid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidWorkspacesWidControlReleaseMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlRelease>>>
    export type PostApiV1TenantsTidWorkspacesWidControlReleaseMutationBody = PostApiV1TenantsTidWorkspacesWidControlReleaseBody
    export type PostApiV1TenantsTidWorkspacesWidControlReleaseMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidWorkspacesWidControlReleaseMutationVariables = {tid: string;wid: string;data: PostApiV1TenantsTidWorkspacesWidControlReleaseBody}

    /**
 * @summary POST /api/v1/tenants/:tid/workspaces/:wid/control/release
 */
export const usePostApiV1TenantsTidWorkspacesWidControlRelease = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlRelease>>, TError,PostApiV1TenantsTidWorkspacesWidControlReleaseMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlRelease>>,
        TError,
        PostApiV1TenantsTidWorkspacesWidControlReleaseMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidWorkspacesWidControlReleaseMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/workspaces/:wid/control/renew
 */
export const postApiV1TenantsTidWorkspacesWidControlRenew = (
    tid: string,
    wid: string,
    postApiV1TenantsTidWorkspacesWidControlRenewBody: PostApiV1TenantsTidWorkspacesWidControlRenewBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<RuntimeControl>(
      {url: `/api/v1/tenants/${tid}/workspaces/${wid}/control/renew`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidWorkspacesWidControlRenewBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidWorkspacesWidControlRenewMutationKey = () => ['postApiV1TenantsTidWorkspacesWidControlRenew'] as const;

export const getPostApiV1TenantsTidWorkspacesWidControlRenewMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlRenew>>, TError,PostApiV1TenantsTidWorkspacesWidControlRenewMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlRenew>>, TError,PostApiV1TenantsTidWorkspacesWidControlRenewMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidWorkspacesWidControlRenewMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlRenew>>, PostApiV1TenantsTidWorkspacesWidControlRenewMutationVariables> = (props) => {
          const {tid,wid,data} = props ?? {};

          return  postApiV1TenantsTidWorkspacesWidControlRenew(tid,wid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidWorkspacesWidControlRenewMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlRenew>>>
    export type PostApiV1TenantsTidWorkspacesWidControlRenewMutationBody = PostApiV1TenantsTidWorkspacesWidControlRenewBody
    export type PostApiV1TenantsTidWorkspacesWidControlRenewMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidWorkspacesWidControlRenewMutationVariables = {tid: string;wid: string;data: PostApiV1TenantsTidWorkspacesWidControlRenewBody}

    /**
 * @summary POST /api/v1/tenants/:tid/workspaces/:wid/control/renew
 */
export const usePostApiV1TenantsTidWorkspacesWidControlRenew = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlRenew>>, TError,PostApiV1TenantsTidWorkspacesWidControlRenewMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidControlRenew>>,
        TError,
        PostApiV1TenantsTidWorkspacesWidControlRenewMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidWorkspacesWidControlRenewMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/workspaces/:wid/force-stop
 */
export const getApiV1TenantsTidWorkspacesWidForceStop = (
    tid: string,
    wid: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1TenantsTidWorkspacesWidForceStop200>(
      {url: `/api/v1/tenants/${tid}/workspaces/${wid}/force-stop`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV1TenantsTidWorkspacesWidForceStopQueryKey = (tid: string,
    wid: string,) => {
    return [
    `/api/v1/tenants/${tid}/workspaces/${wid}/force-stop`
    ] as const;
    }


export const getGetApiV1TenantsTidWorkspacesWidForceStopQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>, TError = ErrorType<Error>>(tid: string,
    wid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidWorkspacesWidForceStopQueryKey(tid,wid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>> = ({ signal }) => getApiV1TenantsTidWorkspacesWidForceStop(tid,wid, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && wid !== null && wid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidWorkspacesWidForceStopQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>>
export type GetApiV1TenantsTidWorkspacesWidForceStopQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidWorkspacesWidForceStop<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>, TError = ErrorType<Error>>(
 tid: string,
    wid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkspacesWidForceStop<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>, TError = ErrorType<Error>>(
 tid: string,
    wid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidWorkspacesWidForceStop<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>, TError = ErrorType<Error>>(
 tid: string,
    wid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/workspaces/:wid/force-stop
 */

export function useGetApiV1TenantsTidWorkspacesWidForceStop<TData = Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>, TError = ErrorType<Error>>(
 tid: string,
    wid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidWorkspacesWidForceStop>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidWorkspacesWidForceStopQueryOptions(tid,wid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/workspaces/:wid/force-stop
 */
export const postApiV1TenantsTidWorkspacesWidForceStop = (
    tid: string,
    wid: string,
    postApiV1TenantsTidWorkspacesWidForceStopBody: PostApiV1TenantsTidWorkspacesWidForceStopBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostApiV1TenantsTidWorkspacesWidForceStop202>(
      {url: `/api/v1/tenants/${tid}/workspaces/${wid}/force-stop`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidWorkspacesWidForceStopBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidWorkspacesWidForceStopMutationKey = () => ['postApiV1TenantsTidWorkspacesWidForceStop'] as const;

export const getPostApiV1TenantsTidWorkspacesWidForceStopMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidForceStop>>, TError,PostApiV1TenantsTidWorkspacesWidForceStopMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidForceStop>>, TError,PostApiV1TenantsTidWorkspacesWidForceStopMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidWorkspacesWidForceStopMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidForceStop>>, PostApiV1TenantsTidWorkspacesWidForceStopMutationVariables> = (props) => {
          const {tid,wid,data} = props ?? {};

          return  postApiV1TenantsTidWorkspacesWidForceStop(tid,wid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidWorkspacesWidForceStopMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidForceStop>>>
    export type PostApiV1TenantsTidWorkspacesWidForceStopMutationBody = PostApiV1TenantsTidWorkspacesWidForceStopBody
    export type PostApiV1TenantsTidWorkspacesWidForceStopMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidWorkspacesWidForceStopMutationVariables = {tid: string;wid: string;data: PostApiV1TenantsTidWorkspacesWidForceStopBody}

    /**
 * @summary POST /api/v1/tenants/:tid/workspaces/:wid/force-stop
 */
export const usePostApiV1TenantsTidWorkspacesWidForceStop = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidForceStop>>, TError,PostApiV1TenantsTidWorkspacesWidForceStopMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidForceStop>>,
        TError,
        PostApiV1TenantsTidWorkspacesWidForceStopMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidWorkspacesWidForceStopMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/workspaces/:wid/restart
 */
export const postApiV1TenantsTidWorkspacesWidRestart = (
    tid: string,
    wid: string,
    postApiV1TenantsTidWorkspacesWidRestartBody: PostApiV1TenantsTidWorkspacesWidRestartBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostApiV1TenantsTidWorkspacesWidRestart202>(
      {url: `/api/v1/tenants/${tid}/workspaces/${wid}/restart`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidWorkspacesWidRestartBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidWorkspacesWidRestartMutationKey = () => ['postApiV1TenantsTidWorkspacesWidRestart'] as const;

export const getPostApiV1TenantsTidWorkspacesWidRestartMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidRestart>>, TError,PostApiV1TenantsTidWorkspacesWidRestartMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidRestart>>, TError,PostApiV1TenantsTidWorkspacesWidRestartMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidWorkspacesWidRestartMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidRestart>>, PostApiV1TenantsTidWorkspacesWidRestartMutationVariables> = (props) => {
          const {tid,wid,data} = props ?? {};

          return  postApiV1TenantsTidWorkspacesWidRestart(tid,wid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidWorkspacesWidRestartMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidRestart>>>
    export type PostApiV1TenantsTidWorkspacesWidRestartMutationBody = PostApiV1TenantsTidWorkspacesWidRestartBody
    export type PostApiV1TenantsTidWorkspacesWidRestartMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidWorkspacesWidRestartMutationVariables = {tid: string;wid: string;data: PostApiV1TenantsTidWorkspacesWidRestartBody}

    /**
 * @summary POST /api/v1/tenants/:tid/workspaces/:wid/restart
 */
export const usePostApiV1TenantsTidWorkspacesWidRestart = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidRestart>>, TError,PostApiV1TenantsTidWorkspacesWidRestartMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidRestart>>,
        TError,
        PostApiV1TenantsTidWorkspacesWidRestartMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidWorkspacesWidRestartMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/workspaces/:wid/start
 */
export const postApiV1TenantsTidWorkspacesWidStart = (
    tid: string,
    wid: string,
    postApiV1TenantsTidWorkspacesWidStartBody: PostApiV1TenantsTidWorkspacesWidStartBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostApiV1TenantsTidWorkspacesWidStart202>(
      {url: `/api/v1/tenants/${tid}/workspaces/${wid}/start`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidWorkspacesWidStartBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidWorkspacesWidStartMutationKey = () => ['postApiV1TenantsTidWorkspacesWidStart'] as const;

export const getPostApiV1TenantsTidWorkspacesWidStartMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidStart>>, TError,PostApiV1TenantsTidWorkspacesWidStartMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidStart>>, TError,PostApiV1TenantsTidWorkspacesWidStartMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidWorkspacesWidStartMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidStart>>, PostApiV1TenantsTidWorkspacesWidStartMutationVariables> = (props) => {
          const {tid,wid,data} = props ?? {};

          return  postApiV1TenantsTidWorkspacesWidStart(tid,wid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidWorkspacesWidStartMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidStart>>>
    export type PostApiV1TenantsTidWorkspacesWidStartMutationBody = PostApiV1TenantsTidWorkspacesWidStartBody
    export type PostApiV1TenantsTidWorkspacesWidStartMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidWorkspacesWidStartMutationVariables = {tid: string;wid: string;data: PostApiV1TenantsTidWorkspacesWidStartBody}

    /**
 * @summary POST /api/v1/tenants/:tid/workspaces/:wid/start
 */
export const usePostApiV1TenantsTidWorkspacesWidStart = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidStart>>, TError,PostApiV1TenantsTidWorkspacesWidStartMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidStart>>,
        TError,
        PostApiV1TenantsTidWorkspacesWidStartMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidWorkspacesWidStartMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Requires matching resource version and no active project operation. Atomically closes new execution admission. Active tickets return 409 resource_in_use without changing admission. Unknown Node activity requires later proof and remains pending/blocked. main Workspace cannot be independently deleted. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/workspaces/:wid/stop
 */
export const postApiV1TenantsTidWorkspacesWidStop = (
    tid: string,
    wid: string,
    postApiV1TenantsTidWorkspacesWidStopBody: PostApiV1TenantsTidWorkspacesWidStopBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostApiV1TenantsTidWorkspacesWidStop202>(
      {url: `/api/v1/tenants/${tid}/workspaces/${wid}/stop`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidWorkspacesWidStopBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidWorkspacesWidStopMutationKey = () => ['postApiV1TenantsTidWorkspacesWidStop'] as const;

export const getPostApiV1TenantsTidWorkspacesWidStopMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidStop>>, TError,PostApiV1TenantsTidWorkspacesWidStopMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidStop>>, TError,PostApiV1TenantsTidWorkspacesWidStopMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidWorkspacesWidStopMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidStop>>, PostApiV1TenantsTidWorkspacesWidStopMutationVariables> = (props) => {
          const {tid,wid,data} = props ?? {};

          return  postApiV1TenantsTidWorkspacesWidStop(tid,wid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidWorkspacesWidStopMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidStop>>>
    export type PostApiV1TenantsTidWorkspacesWidStopMutationBody = PostApiV1TenantsTidWorkspacesWidStopBody
    export type PostApiV1TenantsTidWorkspacesWidStopMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidWorkspacesWidStopMutationVariables = {tid: string;wid: string;data: PostApiV1TenantsTidWorkspacesWidStopBody}

    /**
 * @summary POST /api/v1/tenants/:tid/workspaces/:wid/stop
 */
export const usePostApiV1TenantsTidWorkspacesWidStop = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidStop>>, TError,PostApiV1TenantsTidWorkspacesWidStopMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidWorkspacesWidStop>>,
        TError,
        PostApiV1TenantsTidWorkspacesWidStopMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidWorkspacesWidStopMutationOptions(options), queryClient);
    }
